In [16]:
# import packages

import numpy as np
from numpy import random
from scipy import stats
import pandas as pd

# import r packages (and functions) if needed

import rpy2.robjects as robjects
import rpy2.robjects.packages as rpackages
#rpackages.importr("clusterGeneration")
rpackages.importr("mpower")
#cluster_generation = robjects.packages.importr("clusterGeneration")
mpower = robjects.packages.importr("mpower")

In [2]:
# Fully Synthetic Data Sets (Set up from Künzel et al.)

# 1: Simulate the d-dimensional X.
# 2: Create Potential Outcomes Y(1) and Y(0).
# 3: Simulate Treatment Assignments trough W.

In [23]:
# 1: Simulate the d-dimensional X. #


# Setup parameters
d = 5 # TODO: set dimension according to setup
N = 1000 # TODO: set sample size according to setup

# X Correlation matrix and mean
mean = np.zeros(d) # TODO: set mean according to setup
cov = np.array(mpower.cvine(d=d, alpha = 0.5, beta = 0.5)) # TODO: set cov according to setup

# Simulate X
X = random.multivariate_normal(mean=mean, cov=cov, size=N, check_valid='warn')

In [24]:
# Check X
X

array([[-0.044809  , -0.57742342, -1.17600972,  0.12193732,  0.22906733],
       [ 0.91423651, -2.72894263,  0.28043533, -1.52431219,  1.73310405],
       [-1.33551225,  1.05751876, -0.42657587,  1.036818  , -0.2574132 ],
       ...,
       [-0.037791  ,  1.05714423,  0.47619123, -0.19347704, -0.65761213],
       [-1.35961909, -0.61212145,  1.44987983,  2.38636006,  2.21927434],
       [-1.68482689, -1.45876459, -0.95286503,  1.48455286,  2.24899777]])

In [25]:
# Check cov
cov

array([[ 1.        , -0.34911017, -0.46643655, -0.81691203, -0.3270541 ],
       [-0.34911017,  1.        ,  0.24042546,  0.15571019, -0.69723826],
       [-0.46643655,  0.24042546,  1.        ,  0.66137461,  0.36882644],
       [-0.81691203,  0.15571019,  0.66137461,  1.        ,  0.5673243 ],
       [-0.3270541 , -0.69723826,  0.36882644,  0.5673243 ,  1.        ]])

In [26]:
# 2: Create Potential Outcomes Y(1) and Y(0).

# 2.1 Simulate errors, FIX
e_0 = random.normal(loc=0.0,scale=1.0,size=N)
e_1 = random.normal(loc=0.0,scale=1.0,size=N)

In [ ]:
# Just to make it work, create betas
beta_0 = [2,3,-3,1,4] # TODO: delete or change
beta_1 = [1,1,0,-5,3] # TODO: delete or change

# Create Response Functions
mu_0 = np.matmul(X,beta_0) # TODO: change according to setup
mu_1 = np.matmul(X,beta_1) # TODO: change according to setup

In [ ]:
# 2.2 Create Response Functions

# complex linear cate

# complex non-linear cate

# no treatment effect, global linear

# no treatment effect, piecewise linear

# simple linear cate



In [ ]:
# 2.3 Creat Potential Outcomes, FIX
Y_0 = mu_0 + e_0
Y_1 = mu_1 + e_1

In [27]:
# quick check Y_0
Y_0

array([ 3.16923840e+00, -1.21967992e+00,  7.75987800e-01,  2.81473069e+00,
        3.44315723e+00,  9.87721197e-01, -4.57080694e+00,  8.59574587e-01,
       -2.34227771e+00,  2.12907229e+00, -6.08977138e-01,  3.03967345e+00,
       -1.84065447e+00, -6.03299398e-01, -2.04374528e+00,  2.06837885e+00,
       -2.62599624e+00, -5.87566874e-01, -3.93320682e+00,  2.31325495e+00,
        1.73236985e+00, -3.12237730e-01,  1.23229071e-01,  2.92333377e+00,
        3.34119558e-01, -9.68312638e-01,  3.29452166e+00, -6.22225950e+00,
        8.62636825e-01, -2.72580175e+00, -4.65671431e+00, -1.14883548e+00,
        1.14473610e+00, -2.80510629e+00, -4.39583492e+00,  2.12932436e+00,
        1.94207174e+00,  2.29002674e+00, -1.77585738e+00,  2.28770847e+00,
       -5.51912041e-02, -3.43055907e+00, -2.89522711e+00,  1.74472726e+00,
       -1.04759550e+00,  1.39558468e+00,  5.14271028e-01, -2.68586279e+00,
       -1.52125114e-01,  1.15104838e+00, -2.58711627e+00,  1.18042891e+00,
        1.79808542e+00,  

In [28]:
# Quick Check Y_1
Y_1

array([-1.10311534e+00,  9.61569471e+00, -4.76709507e+00,  9.33302485e-01,
        4.47068805e+00,  3.85226892e+00,  1.99633025e+00,  8.82348997e+00,
        3.30055045e+00, -4.47726406e+00, -3.89916889e+00, -9.98820670e-01,
        5.51256073e+00, -1.05398637e+01, -2.13529210e+00,  7.75899677e+00,
        1.40720390e+00,  6.16361005e+00, -1.71512319e+00,  4.52482480e+00,
       -3.73618605e+00,  1.72153290e+00, -1.87165917e+00,  3.82303297e+00,
        6.11072272e+00, -9.31234617e-02, -3.96841030e+00,  5.31804112e+00,
        3.84003745e+00, -1.67432539e+00, -1.61531173e+00, -7.33746025e-03,
       -1.42829783e+00, -3.27648692e+00,  2.45178050e+00,  1.78769379e+00,
        8.13739574e+00, -5.52833468e+00,  1.87120060e+00, -9.15169823e+00,
        8.43335822e+00,  2.64233087e-01, -1.15732005e+01, -6.17291397e+00,
       -1.31108992e+01,  1.06570380e+01, -4.44435550e+00, -2.81391959e+00,
       -2.12611029e+00, -9.77128317e-03, -2.30264804e+00, -8.62732906e-01,
       -5.43340595e+00, -

In [40]:
# 3.1 Propensity score setups # TODO: change for setup

# i) constant, balanced
e_x = 0.5

# ii) constant, unbalanced
e_x = 0.01

# iii) beta confounded SI6
beta_dist = stats.beta(a=2, b=4) # set beta distribution
beta_values = beta_dist.pdf(X[:,0]) # calculate pdf values for x1
e_x = 1/4*(1+beta_values)

pd.DataFrame(e_x).describe() # summary stats of e_x

0
count  1000.000000
mean      0.339277
std       0.167793
min       0.250000
25%       0.250000
50%       0.250000
75%       0.324228
max       0.777336

In [19]:
# 3.2 Simulate Treatment Assignments trough W

# Simulate Treatment Assignment, FIX
W = random.binomial(size=N, n=1, p=e_x)

# Create Observed Outcome, FIX
ones = np.ones(N)
Y = np.multiply(W,Y_1) + np.multiply(ones-W,Y_0)

In [20]:
# check out observed outcomes
Y

array([ 1.04303442, -8.7163901 ,  6.8355947 , -1.72133214, -8.28021499,
       -5.24568638, 12.72436134,  4.69914253, -1.46360217, -1.37315289])