In [105]:
# import packages
import numpy as np
from numpy import random
from scipy import stats
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split


In [11]:
data = pd.read_csv('/Users/arberimbibaj/dataset_example_indicatorCATE.csv', header=None, index_col=[0])
data = data.to_numpy()
data

array([[  4.907737,  -0.23949 ,   0.202046, ...,  -0.274776,   1.      ,
          8.      ],
       [-15.366406,   0.785973,  -0.935212, ...,   0.146119,   1.      ,
          0.      ],
       [  8.007676,   1.097277,  -0.962872, ...,  -0.791275,   1.      ,
          0.      ],
       ...,
       [ 14.967829,   1.437212,   0.055816, ...,   0.720359,   0.      ,
          0.      ],
       [  8.21161 ,  -0.568252,   0.788217, ...,   0.234121,   0.      ,
          8.      ],
       [ -4.206514,  -0.792531,   1.636563, ...,   2.661297,   0.      ,
          8.      ]])

In [20]:
# train test split
random.shuffle(data)
training, test = data[:700,:], data[700:,:]

In [116]:
# slice dataset by treatment status
training_control = training[training[:,26]==0]
training_treatment = training[training[:,26]==1]

Y_train_control = training_control[:,0]
Y_train_treatment = training_treatment[:,0]

X_train_control = training_control[:,1:26]
X_train_treatment = training_treatment[:,1:26]

X_test = test[:,1:26]
Y_test = test[:,0]

X_train = training[:,1:26]
Y_train = training[:,0]

W_train = training[:,26]
W_test = test[:,26]

tau_test = test[:,27]

In [107]:
X_train_control

array([[ 0.294886, -0.163337,  0.027673, ..., -0.229641, -0.048547,
         0.52518 ],
       [ 0.566179, -0.614477,  1.293208, ...,  2.379063, -1.656574,
         0.631406],
       [ 0.177149,  0.314557, -0.229576, ...,  1.591676, -0.191803,
         1.184389],
       ...,
       [-0.65862 , -0.506026,  0.659462, ..., -0.894909,  0.387133,
        -1.348755],
       [-1.623501,  0.747858, -0.19126 , ...,  0.411393, -0.841022,
         0.377379],
       [-1.235367,  0.545917, -0.435777, ..., -1.520365, -0.428098,
        -0.945772]])

In [108]:
X_train_treatment

array([[ 0.251765, -0.694423,  0.497623, ..., -1.56961 ,  0.389306,
        -0.497222],
       [-0.491173,  0.948584, -0.950545, ...,  1.133758,  0.210477,
         1.288609],
       [-0.272609,  0.037272, -0.389901, ..., -1.371809,  1.630698,
        -1.49329 ],
       ...,
       [-1.811231,  1.509064, -0.846039, ...,  0.682702, -2.009512,
         0.794268],
       [ 0.592685, -0.496693,  0.074878, ..., -0.9846  ,  1.695029,
        -1.363399],
       [-0.917536,  0.389146,  0.085446, ...,  0.745745, -0.192563,
         0.296584]])

In [109]:
Y_train_control

array([-5.4543210e+00,  4.4881430e+00,  3.3099400e-01, -7.4510900e+00,
       -5.0663870e+00,  4.4717420e+00,  1.8622180e+00, -1.8147715e+01,
       -8.1602090e+00,  1.9083127e+01, -4.2777760e+00, -6.5813320e+00,
       -2.4801850e+00,  1.0034232e+01, -1.2172199e+01,  2.4070690e+00,
       -1.7248146e+01,  1.2241120e+00,  1.2569779e+01, -1.0834601e+01,
       -7.2448980e+00,  6.8389760e+00,  9.6275180e+00,  2.4209175e+01,
       -4.6611510e+00, -1.3942219e+01, -1.4006161e+01, -1.3682700e+00,
       -4.0251690e+00, -7.3834690e+00,  4.0338680e+00,  8.9059900e-01,
        1.3743900e-01,  1.4794211e+01,  9.1837180e+00,  5.7205630e+00,
        2.0845347e+01,  2.3910412e+01,  1.5218092e+01, -4.2169600e-01,
       -1.5785149e+01, -9.4126060e+00,  5.2267410e+00,  8.9062680e+00,
       -9.7038340e+00,  2.4782091e+01, -5.7264160e+00,  2.5042145e+01,
        1.5657005e+01, -1.8541497e+01, -4.2027850e+00, -2.4314467e+01,
        8.8023110e+00, -1.6422043e+01,  1.6449797e+01,  1.5457198e+01,
      

In [110]:
Y_train_treatment

array([-13.752677,  11.698583,   5.815386,   3.610941,  19.132886,
         1.639132,   4.36955 ,  26.43854 ,  17.704955,  -8.647979,
       -17.003424, -10.802114,   2.498613,   3.557231,  13.061589,
        35.690089, -11.765541,  15.428557,   9.171301,  13.809747,
       -15.808902, -14.382371,   7.020273,  11.34338 ,  -2.128127,
        36.047091,   9.507009,  15.638408,  -7.627164,  -5.380992,
         1.726438,   0.564602,  -7.367355,   0.901053,   8.832167,
        21.893314,   3.769253, -23.40251 ,  35.931806,  -6.318079,
        -6.009898,   4.907737,  -1.670179,   0.66932 ,  -8.862359,
        21.549357, -10.26454 ,   4.010534,  -1.076108,  -0.454849,
         6.922942,   1.919046,  30.086927, -21.477146,   1.548831,
        22.223798,  -7.215069,   2.293594, -16.11202 ,   4.311981,
        23.090678,  14.799757,  -1.012731,  -3.227414,  30.056251,
        20.413356,  15.405765,  15.674313,  15.348907,  24.450417,
        19.505806,  16.349053,  -5.369789,  -9.920115,  -4.932

In [111]:
X_train

array([[ 0.294886, -0.163337,  0.027673, ..., -0.229641, -0.048547,
         0.52518 ],
       [ 0.251765, -0.694423,  0.497623, ..., -1.56961 ,  0.389306,
        -0.497222],
       [ 0.566179, -0.614477,  1.293208, ...,  2.379063, -1.656574,
         0.631406],
       ...,
       [-1.235367,  0.545917, -0.435777, ..., -1.520365, -0.428098,
        -0.945772],
       [ 0.592685, -0.496693,  0.074878, ..., -0.9846  ,  1.695029,
        -1.363399],
       [-0.917536,  0.389146,  0.085446, ...,  0.745745, -0.192563,
         0.296584]])

In [117]:
W_train

array([0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 1., 1.

In [112]:
Y_train

array([-5.4543210e+00, -1.3752677e+01,  4.4881430e+00,  3.3099400e-01,
        1.1698583e+01, -7.4510900e+00, -5.0663870e+00,  5.8153860e+00,
        3.6109410e+00,  4.4717420e+00,  1.9132886e+01,  1.6391320e+00,
        1.8622180e+00, -1.8147715e+01,  4.3695500e+00, -8.1602090e+00,
        1.9083127e+01,  2.6438540e+01, -4.2777760e+00, -6.5813320e+00,
        1.7704955e+01, -8.6479790e+00, -2.4801850e+00,  1.0034232e+01,
       -1.2172199e+01,  2.4070690e+00, -1.7003424e+01, -1.7248146e+01,
       -1.0802114e+01,  1.2241120e+00,  2.4986130e+00,  3.5572310e+00,
        1.2569779e+01,  1.3061589e+01,  3.5690089e+01, -1.0834601e+01,
       -7.2448980e+00, -1.1765541e+01,  6.8389760e+00,  1.5428557e+01,
        9.6275180e+00,  2.4209175e+01, -4.6611510e+00, -1.3942219e+01,
        9.1713010e+00,  1.3809747e+01, -1.5808902e+01, -1.4382371e+01,
        7.0202730e+00,  1.1343380e+01, -2.1281270e+00, -1.4006161e+01,
       -1.3682700e+00,  3.6047091e+01, -4.0251690e+00, -7.3834690e+00,
      

In [113]:
X_test

array([[ 3.026174, -3.066147,  2.628606, ...,  0.552416,  1.935879,
        -1.623676],
       [-0.211909,  0.50815 , -0.754088, ..., -1.245839,  0.187456,
        -0.69344 ],
       [-1.849185,  0.648927, -0.187384, ..., -0.350891, -0.506473,
        -0.522948],
       ...,
       [ 1.60301 , -1.040473,  0.757985, ...,  0.307271,  0.87984 ,
        -0.816457],
       [ 1.261045, -0.271647, -0.125924, ..., -0.243769,  1.004678,
        -0.468852],
       [-0.526341,  0.99638 , -0.8405  , ...,  0.529766, -0.473872,
        -0.034037]])

In [118]:
W_test

array([1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 1., 1., 1.

In [114]:
Y_test

array([ 3.6784530e+00,  1.9506746e+01, -6.0500000e-03, -1.2276900e-01,
        4.5352730e+00,  1.5710635e+01,  1.0273500e-01,  1.4967829e+01,
       -1.4950753e+01, -7.3862840e+00, -3.9514070e+00,  2.1134588e+01,
       -8.0846590e+00,  2.9192350e+00, -1.0039914e+01,  1.1020995e+01,
        1.8337640e+01,  1.5641645e+01,  2.1500170e+00,  2.7559963e+01,
        2.4212280e+00,  5.6713550e+00,  3.9320150e+00, -5.6497110e+00,
        1.5615589e+01, -6.0026010e+00, -3.9612630e+00,  1.4592240e+01,
        1.2620912e+01,  2.0668025e+01,  1.6450622e+01,  4.6515590e+00,
        9.6654980e+00,  1.8422097e+01,  9.6746670e+00, -4.1656090e+00,
        3.3424120e+00,  2.5664341e+01, -1.5771570e+00,  4.4301800e-01,
        6.2192490e+00, -2.2074146e+01, -1.7357487e+01,  3.8455120e+00,
        1.0181567e+01, -9.8729760e+00,  1.8100750e+00,  1.7137210e+00,
       -1.0976341e+01, -2.8797060e+00, -3.1072080e+00,  1.8723493e+01,
        1.1764144e+01,  9.4077360e+00,  5.1232600e+00,  9.0535810e+00,
      

In [115]:
tau_test

array([0., 8., 8., 0., 0., 8., 0., 0., 0., 0., 8., 8., 8., 8., 0., 8., 8.,
       0., 8., 8., 0., 8., 0., 0., 0., 0., 0., 8., 8., 0., 0., 8., 8., 0.,
       8., 8., 0., 8., 8., 0., 8., 0., 0., 0., 0., 0., 8., 0., 0., 8., 8.,
       0., 0., 0., 8., 0., 8., 8., 0., 0., 8., 0., 8., 8., 0., 0., 0., 8.,
       0., 0., 0., 0., 0., 0., 8., 0., 8., 8., 0., 8., 0., 8., 0., 0., 0.,
       8., 0., 0., 0., 0., 8., 0., 0., 0., 0., 0., 8., 0., 0., 0., 0., 0.,
       8., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 8., 8., 0., 0., 0.,
       8., 0., 0., 0., 0., 0., 8., 8., 8., 8., 0., 0., 0., 0., 0., 0., 8.,
       8., 8., 0., 8., 8., 8., 0., 0., 8., 0., 8., 0., 8., 8., 0., 0., 8.,
       8., 0., 8., 8., 8., 0., 8., 0., 8., 0., 8., 8., 0., 0., 0., 8., 8.,
       8., 8., 0., 0., 8., 0., 0., 8., 0., 8., 0., 0., 8., 0., 8., 8., 0.,
       0., 8., 8., 8., 0., 8., 0., 8., 8., 0., 8., 8., 0., 0., 0., 0., 8.,
       8., 8., 8., 8., 8., 0., 8., 0., 8., 8., 8., 8., 0., 0., 0., 8., 8.,
       0., 0., 0., 0., 8.

# T-Learner

In [95]:
# T-Learner (example with Random Forest)

# mu_0
t_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
t_learner_mu0.fit(X_train_control,Y_train_control)
t_mu_0_hat = t_learner_mu0.predict(X_test)

# mu_1
t_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
t_learner_mu1.fit(X_train_treatment,Y_train_treatment)
t_mu_1_hat = t_learner_mu1.predict(X_test)
# Prediction = mu_1 - mu_0
t_tau_hat = t_mu_1_hat - t_mu_0_hat
print(t_tau_hat)

[-6.35508030e+00  5.95641212e+00  1.30461467e+01 -2.29355780e+00
 -5.30831477e+00  4.88950948e+00 -6.69970280e-01  2.74324616e+00
 -6.33822340e-01  7.57443322e+00  1.08160976e+01  6.96295248e+00
  1.00806459e+01  3.79743045e+00  4.28715473e+00  7.39491966e+00
  2.01933282e+00  2.84545226e+00  8.30492484e+00  4.60015402e+00
 -6.18766560e-01  1.13677603e+01 -3.97604406e+00 -6.12118688e+00
 -4.29086190e-01  1.34475188e+00  2.20653906e+00  4.62263534e+00
  4.76787697e+00  1.34109564e+00 -4.14229750e-01  6.46288826e+00
  7.94616236e+00 -6.79788770e-01  1.07403347e+01  1.17370627e+01
  4.47134089e+00  9.31527700e+00  1.11403859e+01  1.67328112e+00
  6.43426553e+00  3.21676370e-01 -9.23441540e-01 -1.02983960e+00
 -9.61820012e+00  1.27667028e+00  6.62245403e+00 -2.86758301e+00
  5.65114389e+00  9.65963328e+00  4.97015072e+00 -4.17831128e+00
 -7.09857036e+00 -1.22472643e+00  3.86688549e+00 -5.41936055e+00
  8.29895429e+00  8.96439579e+00  8.54164590e+00 -1.92692722e+00
  1.74656283e+01 -3.03125

In [96]:
# mean squared error
((t_tau_hat - tau_test)**2).mean()

11.390083790523878

TODO: Create an example csv dataset with the true values for CATE aka tau!

# S-Learner

In [97]:
# set training and test features for the S-Learner (it views W as no different from other X's)
X_W_train = training[:,1:27]
X_test_0 = np.concatenate((test[:,1:26],np.zeros((300,1))), axis=1)
X_test_1 = np.concatenate((test[:,1:26],np.ones((300,1))), axis=1)
Y_train = training[:,0]

In [98]:
X_test_0

array([[ 3.026174, -3.066147,  2.628606, ...,  1.935879, -1.623676,
         0.      ],
       [-0.211909,  0.50815 , -0.754088, ...,  0.187456, -0.69344 ,
         0.      ],
       [-1.849185,  0.648927, -0.187384, ..., -0.506473, -0.522948,
         0.      ],
       ...,
       [ 1.60301 , -1.040473,  0.757985, ...,  0.87984 , -0.816457,
         0.      ],
       [ 1.261045, -0.271647, -0.125924, ...,  1.004678, -0.468852,
         0.      ],
       [-0.526341,  0.99638 , -0.8405  , ..., -0.473872, -0.034037,
         0.      ]])

In [99]:
X_test_1

array([[ 3.026174, -3.066147,  2.628606, ...,  1.935879, -1.623676,
         1.      ],
       [-0.211909,  0.50815 , -0.754088, ...,  0.187456, -0.69344 ,
         1.      ],
       [-1.849185,  0.648927, -0.187384, ..., -0.506473, -0.522948,
         1.      ],
       ...,
       [ 1.60301 , -1.040473,  0.757985, ...,  0.87984 , -0.816457,
         1.      ],
       [ 1.261045, -0.271647, -0.125924, ...,  1.004678, -0.468852,
         1.      ],
       [-0.526341,  0.99638 , -0.8405  , ..., -0.473872, -0.034037,
         1.      ]])

In [100]:
Y_train

array([-5.4543210e+00, -1.3752677e+01,  4.4881430e+00,  3.3099400e-01,
        1.1698583e+01, -7.4510900e+00, -5.0663870e+00,  5.8153860e+00,
        3.6109410e+00,  4.4717420e+00,  1.9132886e+01,  1.6391320e+00,
        1.8622180e+00, -1.8147715e+01,  4.3695500e+00, -8.1602090e+00,
        1.9083127e+01,  2.6438540e+01, -4.2777760e+00, -6.5813320e+00,
        1.7704955e+01, -8.6479790e+00, -2.4801850e+00,  1.0034232e+01,
       -1.2172199e+01,  2.4070690e+00, -1.7003424e+01, -1.7248146e+01,
       -1.0802114e+01,  1.2241120e+00,  2.4986130e+00,  3.5572310e+00,
        1.2569779e+01,  1.3061589e+01,  3.5690089e+01, -1.0834601e+01,
       -7.2448980e+00, -1.1765541e+01,  6.8389760e+00,  1.5428557e+01,
        9.6275180e+00,  2.4209175e+01, -4.6611510e+00, -1.3942219e+01,
        9.1713010e+00,  1.3809747e+01, -1.5808902e+01, -1.4382371e+01,
        7.0202730e+00,  1.1343380e+01, -2.1281270e+00, -1.4006161e+01,
       -1.3682700e+00,  3.6047091e+01, -4.0251690e+00, -7.3834690e+00,
      

In [101]:
# S-learner (example with Random Forest)

# mu_x
s_learner = RandomForestRegressor(max_depth=100, random_state=0)
s_learner.fit(X_W_train,Y_train)

# mu_0_hat
s_mu_0_hat = s_learner.predict(X_test_0)

# mu_1_hat
s_mu_1_hat = s_learner.predict(X_test_1)

# tau_hat
s_tau_hat = s_mu_1_hat - s_mu_0_hat
s_tau_hat


array([-2.15420270e-01,  1.53341202e+00,  7.71792010e-01,  8.86894900e-02,
       -6.46933670e-01,  1.32118514e+00,  4.18866970e-01,  1.63958744e+00,
       -2.09591830e-01,  1.30259900e-01,  4.43806707e+00,  3.75567686e+00,
        1.13338234e+00,  1.27353987e+00,  1.89510250e-01,  1.37435884e+00,
        6.14565760e-01, -1.71958530e-01,  3.17008371e+00,  1.18842214e+00,
       -1.67219730e-01,  4.59378486e+00, -2.98788180e-01, -8.61930600e-02,
       -2.93853000e-01, -1.35990000e-03,  4.41812790e-01,  2.14049245e+00,
        1.15570277e+00,  9.54038620e-01, -2.18274000e-02,  2.80189555e+00,
        3.72207010e+00, -1.01459430e-01,  7.12719481e+00,  1.45269185e+00,
       -5.67819900e-02,  5.05876250e+00,  3.44870215e+00, -1.92584810e-01,
        4.34557563e+00, -5.35784000e-02, -2.11106810e-01,  1.96004680e-01,
       -1.17863910e-01,  1.48589400e-01,  1.68349598e+00, -6.95666000e-02,
        7.74865700e-02,  2.21698663e+00,  1.43068791e+00,  2.89561740e-01,
       -4.04336190e-01, -

In [102]:
# mean squared error
((s_tau_hat - tau_test)**2).mean()

16.068847283733916

# X-Learner

In [124]:
### X-Learner

# mu_0 (same procedure as for t-learner, maybe can speed up process)
x_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
x_learner_mu0.fit(X_train_control,Y_train_control)

# mu_1 (same procedure as for t-learner, maybe can speed up process)
x_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
x_learner_mu1.fit(X_train_treatment,Y_train_treatment)

# compute imputed treatment effect D_0 and D_1
# d_0
imputed_0 = x_learner_mu1.predict(X_train_control) - Y_train_control

# d_1
imputed_1 = Y_train_treatment - x_learner_mu0.predict(X_train_treatment)

# regress imputed on X
# tau_hat_0
x_tau_0_hat = RandomForestRegressor(max_depth=100, random_state=0)
x_tau_0_hat.fit(X_train_control ,imputed_0)

# tau_hat_1
x_tau_1_hat = RandomForestRegressor(max_depth=100, random_state=0)
x_tau_1_hat.fit(X_train_treatment ,imputed_1)

# estimate e_x to use as g_x
g_x_hat = RandomForestClassifier(max_depth=100, random_state=0)
g_x_hat.fit(X_train,W_train)
probabilities = g_x_hat.predict_proba(X_test)
probas_1 = probabilities[:,1]
probas_0 = probabilities[:,0]

# final estimator of tau
x_tau_hat = probas_1 * x_tau_0_hat.predict(X_test) + probas_0 * x_tau_1_hat.predict(X_test)
x_tau_hat


array([-2.29321217e+00,  7.32715999e+00,  9.14025322e+00, -2.98848670e-01,
       -1.87927606e-01,  7.13850455e+00,  9.29607862e-03, -1.36385072e+00,
        1.79378604e+00,  1.71368506e+00,  8.87600432e+00,  6.32390263e+00,
        8.45775640e+00,  6.59308875e+00,  6.91819002e-02,  1.05874928e+01,
        4.50361518e+00,  4.35294414e-01,  9.90748320e+00,  4.03692376e+00,
        3.99929828e-01,  9.07467213e+00, -5.19675039e-01, -2.18972931e+00,
       -1.68175307e+00, -2.29568330e-01,  2.56517401e+00,  5.82791737e+00,
        7.01558689e+00, -2.47274418e-01, -7.81937900e-01,  7.45440430e+00,
        6.82549367e+00,  2.64554462e-01,  8.63795502e+00,  6.64795567e+00,
        4.80159971e-01,  9.34501174e+00,  7.77735201e+00,  4.89659992e-01,
        7.59110821e+00, -7.38774787e-01,  6.36810575e-02, -4.24311564e-01,
       -3.39366425e+00,  1.01281937e+00,  9.00880661e+00, -7.16022209e-01,
        6.16938118e-02,  7.52476972e+00,  7.99504221e+00, -1.48448358e-01,
       -2.09678868e+00, -

In [125]:
# mean squared error (much lower here!)
((x_tau_hat - tau_test)**2).mean()

2.46475713849908

In [ ]:
# R-Learner

In [ ]:
# DR-Learner

In [ ]:
# RA-Learner

In [ ]:
# PW-Learner

In [ ]:
# F-Learner

In [ ]:
# U-Learner