In [1]:
# import packages
import numpy as np
from numpy import random
from scipy import stats
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split


In [2]:
data = pd.read_csv('/Users/arberimbibaj/dataset_example_indicatorCATE.csv', header=None, index_col=[0])
data = data.to_numpy()
data

array([[  4.907737,  -0.23949 ,   0.202046, ...,  -0.274776,   1.      ,
          8.      ],
       [-15.366406,   0.785973,  -0.935212, ...,   0.146119,   1.      ,
          0.      ],
       [  8.007676,   1.097277,  -0.962872, ...,  -0.791275,   1.      ,
          0.      ],
       ...,
       [ 14.967829,   1.437212,   0.055816, ...,   0.720359,   0.      ,
          0.      ],
       [  8.21161 ,  -0.568252,   0.788217, ...,   0.234121,   0.      ,
          8.      ],
       [ -4.206514,  -0.792531,   1.636563, ...,   2.661297,   0.      ,
          8.      ]])

In [3]:
# train test split
random.shuffle(data)
training, test = data[:700,:], data[700:,:]

In [4]:
# slice dataset by treatment status
training_control = training[training[:,26]==0]
training_treatment = training[training[:,26]==1]

# Y_train by treatment status
Y_train_control = training_control[:,0]
Y_train_treatment = training_treatment[:,0]

# X_train by treatment status
X_train_control = training_control[:,1:26]
X_train_treatment = training_treatment[:,1:26]

# X and Y test
X_test = test[:,1:26]
Y_test = test[:,0]

# X_train and Y_train (no split by treatment status)
X_train = training[:,1:26]
Y_train = training[:,0]

# W_train and W_test
W_train = training[:,26]
W_test = test[:,26]

# tau_test
tau_test = test[:,27]

In [5]:
X_train_control

array([[-0.73668 , -0.262747,  0.323882, ..., -0.324489,  0.457693,
        -0.500303],
       [ 0.04784 , -0.22871 ,  0.377257, ...,  0.502492,  0.105388,
        -0.541156],
       [ 0.060759,  0.56992 , -0.119918, ...,  1.947485, -1.486273,
         0.775501],
       ...,
       [-0.468731,  0.637259, -0.986706, ..., -1.745328,  0.244177,
        -0.161777],
       [-0.371236,  0.43829 , -0.380551, ..., -0.117452, -0.038594,
        -0.3032  ],
       [ 0.729611,  0.670044, -1.667667, ..., -2.002874,  1.1066  ,
         0.054762]])

In [6]:
X_train_treatment

array([[-1.040735,  0.376025, -0.285208, ..., -0.163427, -0.550018,
         1.335978],
       [ 0.443016, -0.63676 ,  0.513939, ..., -0.686854,  1.083426,
        -1.154605],
       [-1.077578,  1.194336, -0.984679, ..., -0.50638 , -0.594609,
         0.085542],
       ...,
       [ 0.288442,  0.332062, -0.341198, ...,  0.553212, -0.31896 ,
         0.307164],
       [-0.66967 , -0.380692,  0.72659 , ..., -0.194397, -0.607058,
        -0.630709],
       [ 0.969699,  0.369004, -0.66519 , ...,  1.029889, -0.016511,
         1.04934 ]])

In [7]:
Y_train_control

array([-1.2112846e+01,  4.1205240e+00,  1.4901125e+01,  5.7058970e+00,
       -8.8482000e-01,  9.5416500e-01, -2.0921542e+01, -7.4510900e+00,
       -1.2328640e+00,  4.1978900e-01,  1.3743900e-01,  6.8389760e+00,
        1.8655851e+01, -5.7974410e+00,  4.0166540e+00, -8.1602090e+00,
       -1.3265980e+00,  1.4157402e+01, -1.1951283e+01,  1.1127334e+01,
       -1.6845198e+01, -2.0539934e+01,  1.5641645e+01, -6.4866580e+00,
       -1.6533996e+01, -4.6611510e+00,  9.2620220e+00, -1.6538463e+01,
        1.4109718e+01, -7.9171100e+00,  4.0693450e+00,  4.3782330e+00,
        2.3907990e+00, -1.3942219e+01, -1.2172199e+01,  2.1642318e+01,
       -7.3862840e+00,  9.0037150e+00, -6.7612510e+00, -1.0772629e+01,
        2.4070690e+00, -1.5944500e+01, -3.1091800e+00, -8.8000700e-01,
        1.8723493e+01, -1.1226910e+01,  4.0338680e+00,  3.9320150e+00,
       -1.6422043e+01, -8.0846590e+00,  6.1413470e+00, -1.7210161e+01,
       -2.2476329e+01, -2.2396780e+00, -4.2777760e+00, -3.3959420e+00,
      

In [8]:
Y_train_treatment

array([-1.8365990e+01,  3.3424120e+00,  1.7704955e+01,  3.6320080e+00,
       -4.7980920e+00,  1.4456110e+00,  1.7386500e-01,  1.0494211e+01,
        1.0225313e+01,  3.8922571e+01,  6.1426070e+00,  1.2442084e+01,
       -7.6745090e+00, -1.6895450e+00,  6.1932970e+00, -2.3435600e+00,
        1.9505806e+01, -3.3261300e-01,  1.1959542e+01, -5.3809920e+00,
        2.1500170e+00,  1.5615589e+01, -8.5334460e+00,  2.4121151e+01,
        1.2399746e+01,  1.2886949e+01,  2.2285164e+01, -1.4165914e+01,
        5.2192880e+00, -1.1874091e+01,  4.4301800e-01,  1.2423321e+01,
       -1.5593609e+01,  5.3616950e+00, -2.1477146e+01,  2.3656920e+00,
        1.3953920e+01, -1.8364080e+00,  9.0105300e-01, -2.7976570e+00,
        2.3688359e+01,  1.7528210e+01, -3.8713000e+00,  1.0273500e-01,
        5.6460200e-01,  6.6412680e+00,  5.6244390e+00, -1.4239510e+01,
       -2.7085525e+01,  9.2879140e+00,  1.6548698e+01,  3.0056251e+01,
        4.3119810e+00, -1.6792012e+01,  2.2935940e+00,  2.6658826e+01,
      

In [9]:
X_train

array([[-0.73668 , -0.262747,  0.323882, ..., -0.324489,  0.457693,
        -0.500303],
       [-1.040735,  0.376025, -0.285208, ..., -0.163427, -0.550018,
         1.335978],
       [ 0.443016, -0.63676 ,  0.513939, ..., -0.686854,  1.083426,
        -1.154605],
       ...,
       [ 0.969699,  0.369004, -0.66519 , ...,  1.029889, -0.016511,
         1.04934 ],
       [-0.371236,  0.43829 , -0.380551, ..., -0.117452, -0.038594,
        -0.3032  ],
       [ 0.729611,  0.670044, -1.667667, ..., -2.002874,  1.1066  ,
         0.054762]])

In [10]:
W_train

array([0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 0.

In [11]:
Y_train

array([-1.2112846e+01, -1.8365990e+01,  3.3424120e+00,  1.7704955e+01,
        4.1205240e+00,  3.6320080e+00, -4.7980920e+00,  1.4456110e+00,
        1.4901125e+01,  1.7386500e-01,  1.0494211e+01,  5.7058970e+00,
        1.0225313e+01, -8.8482000e-01,  3.8922571e+01,  9.5416500e-01,
       -2.0921542e+01, -7.4510900e+00,  6.1426070e+00, -1.2328640e+00,
        1.2442084e+01, -7.6745090e+00, -1.6895450e+00,  6.1932970e+00,
        4.1978900e-01, -2.3435600e+00,  1.3743900e-01,  1.9505806e+01,
        6.8389760e+00,  1.8655851e+01, -5.7974410e+00, -3.3261300e-01,
        1.1959542e+01, -5.3809920e+00,  4.0166540e+00,  2.1500170e+00,
       -8.1602090e+00,  1.5615589e+01, -8.5334460e+00,  2.4121151e+01,
       -1.3265980e+00,  1.2399746e+01,  1.2886949e+01,  2.2285164e+01,
       -1.4165914e+01,  5.2192880e+00, -1.1874091e+01,  4.4301800e-01,
        1.4157402e+01, -1.1951283e+01,  1.1127334e+01, -1.6845198e+01,
       -2.0539934e+01,  1.2423321e+01, -1.5593609e+01,  1.5641645e+01,
      

In [12]:
X_test

array([[ 0.880172, -0.343095, -0.081335, ...,  0.42759 ,  0.555915,
         0.816875],
       [-0.917536,  0.389146,  0.085446, ...,  0.745745, -0.192563,
         0.296584],
       [ 0.426836, -0.100339, -0.418822, ..., -1.406617,  0.747568,
         0.080475],
       ...,
       [-1.181248,  0.556598, -0.428226, ..., -0.449594,  0.110424,
        -0.130239],
       [ 1.437212,  0.055816, -0.808735, ..., -0.657956,  0.417614,
         0.720359],
       [ 1.023972,  0.145602, -0.823875, ..., -0.323625,  1.409252,
         0.087279]])

In [13]:
W_test

array([0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 1.

In [14]:
Y_test

array([ 9.6871100e-01,  2.6709040e+00, -1.3682700e+00, -1.6412666e+01,
        1.4326930e+01, -1.0039914e+01,  1.5325600e+00,  5.0865700e-01,
       -1.0857179e+01, -4.1913970e+00,  2.2833590e+00,  1.1698583e+01,
        1.3141581e+01, -9.8435900e-01,  3.2415080e+00, -1.0220641e+01,
        2.0256116e+01,  1.2620912e+01,  1.1244057e+01, -2.6898300e+00,
        3.4385880e+01,  1.0142397e+01, -1.2412180e+01, -4.3611400e+00,
        1.6991620e+01, -1.2793475e+01,  2.5128080e+00,  1.3096910e+00,
       -1.5785149e+01,  1.6078372e+01, -1.4663935e+01, -1.0787159e+01,
        9.7939700e+00,  1.7264380e+00,  1.2912181e+01,  5.5199140e+00,
       -7.7805500e-01, -1.1765541e+01,  5.0191900e-01, -1.6965860e+00,
        4.9828560e+00,  6.6318550e+00, -2.2827590e+00,  3.3320700e+00,
        4.8280080e+00,  1.6794400e-01,  2.4450417e+01,  2.8594070e+00,
        1.3749180e+01,  9.7082670e+00,  2.0396940e+00,  1.3622356e+01,
        2.0602528e+01, -3.1722912e+01,  9.1273420e+00,  7.0605900e-01,
      

In [15]:
tau_test

array([0., 8., 0., 0., 8., 0., 8., 8., 0., 8., 8., 8., 0., 8., 8., 0., 8.,
       8., 8., 0., 8., 8., 0., 0., 0., 8., 0., 0., 0., 8., 0., 0., 8., 8.,
       0., 8., 8., 8., 0., 0., 8., 0., 0., 8., 8., 8., 8., 0., 0., 0., 8.,
       8., 0., 0., 8., 8., 8., 0., 0., 0., 0., 0., 0., 0., 8., 8., 8., 0.,
       0., 8., 0., 0., 0., 8., 0., 8., 8., 0., 8., 8., 0., 0., 8., 8., 0.,
       0., 0., 0., 0., 8., 0., 0., 0., 0., 0., 0., 0., 8., 8., 0., 8., 0.,
       0., 8., 8., 0., 0., 8., 0., 0., 8., 8., 8., 0., 8., 0., 0., 8., 0.,
       0., 8., 0., 0., 8., 8., 8., 8., 0., 0., 8., 8., 8., 8., 8., 8., 8.,
       0., 8., 8., 0., 0., 8., 0., 8., 0., 0., 8., 0., 8., 8., 0., 8., 0.,
       8., 8., 0., 8., 8., 8., 8., 0., 0., 8., 0., 0., 8., 8., 0., 8., 8.,
       0., 8., 0., 8., 8., 8., 8., 0., 8., 8., 0., 0., 8., 0., 0., 8., 8.,
       0., 0., 8., 0., 8., 0., 8., 8., 8., 0., 0., 8., 8., 8., 0., 8., 8.,
       8., 8., 0., 8., 8., 8., 0., 8., 0., 8., 8., 0., 0., 8., 0., 8., 8.,
       0., 0., 0., 8., 0.

# T-Learner

In [17]:
# T-Learner (example with Random Forest)

# mu_0
t_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
t_learner_mu0.fit(X_train_control,Y_train_control)
t_mu_0_hat = t_learner_mu0.predict(X_test)

# mu_1
t_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
t_learner_mu1.fit(X_train_treatment,Y_train_treatment)
t_mu_1_hat = t_learner_mu1.predict(X_test)
# Prediction = mu_1 - mu_0
t_tau_hat = t_mu_1_hat - t_mu_0_hat
t_tau_hat

array([ 1.38448458,  4.56797266, -3.43175701, -4.10657662, 10.95313939,
        0.31492848,  8.95425338, 10.54165472,  0.20137052, 12.39489346,
        6.26145561, 11.36944629, -3.11972068, 10.43894919, 11.92885288,
       -1.02559194,  7.17551426, 12.10050005,  6.56027967,  1.42424754,
        4.8643617 ,  7.89228584,  3.23312291, -0.81790157,  1.05562869,
        4.78535332, -6.14181525, -0.7312811 ,  1.74663512,  3.06372545,
       -0.21949763,  1.93307983,  8.39741023, 15.13941979,  1.0300402 ,
        9.04697544, 11.75486935, 13.87229768, -2.2833139 , -1.75016796,
        9.12636592, -1.72555196, -2.34340582,  8.45189199,  5.57566554,
        9.28603135,  6.33425007, -0.25830342,  2.59896473,  4.78966241,
        4.86109961,  8.04282726, -0.86545304, -5.61749504,  1.37050209,
       -1.0999961 ,  4.04882855,  3.0866375 ,  0.04113865,  0.98705107,
        0.94989496,  0.21567556, -1.64162302,  5.86595455,  9.60605204,
        7.09407681,  4.78044717, -2.50838   ,  3.0009037 ,  9.35

In [18]:
# mean squared error
((t_tau_hat - tau_test)**2).mean()

10.194682497093364

# S-Learner

In [19]:
### S-Learner

In [20]:
# set training and test features for the S-Learner (it views W as no different from other X's)
X_W_train = training[:,1:27]
X_test_0 = np.concatenate((test[:,1:26],np.zeros((300,1))), axis=1)
X_test_1 = np.concatenate((test[:,1:26],np.ones((300,1))), axis=1)

In [21]:
X_test_0

array([[ 0.880172, -0.343095, -0.081335, ...,  0.555915,  0.816875,
         0.      ],
       [-0.917536,  0.389146,  0.085446, ..., -0.192563,  0.296584,
         0.      ],
       [ 0.426836, -0.100339, -0.418822, ...,  0.747568,  0.080475,
         0.      ],
       ...,
       [-1.181248,  0.556598, -0.428226, ...,  0.110424, -0.130239,
         0.      ],
       [ 1.437212,  0.055816, -0.808735, ...,  0.417614,  0.720359,
         0.      ],
       [ 1.023972,  0.145602, -0.823875, ...,  1.409252,  0.087279,
         0.      ]])

In [22]:
X_test_1

array([[ 0.880172, -0.343095, -0.081335, ...,  0.555915,  0.816875,
         1.      ],
       [-0.917536,  0.389146,  0.085446, ..., -0.192563,  0.296584,
         1.      ],
       [ 0.426836, -0.100339, -0.418822, ...,  0.747568,  0.080475,
         1.      ],
       ...,
       [-1.181248,  0.556598, -0.428226, ...,  0.110424, -0.130239,
         1.      ],
       [ 1.437212,  0.055816, -0.808735, ...,  0.417614,  0.720359,
         1.      ],
       [ 1.023972,  0.145602, -0.823875, ...,  1.409252,  0.087279,
         1.      ]])

In [23]:
Y_train

array([-1.2112846e+01, -1.8365990e+01,  3.3424120e+00,  1.7704955e+01,
        4.1205240e+00,  3.6320080e+00, -4.7980920e+00,  1.4456110e+00,
        1.4901125e+01,  1.7386500e-01,  1.0494211e+01,  5.7058970e+00,
        1.0225313e+01, -8.8482000e-01,  3.8922571e+01,  9.5416500e-01,
       -2.0921542e+01, -7.4510900e+00,  6.1426070e+00, -1.2328640e+00,
        1.2442084e+01, -7.6745090e+00, -1.6895450e+00,  6.1932970e+00,
        4.1978900e-01, -2.3435600e+00,  1.3743900e-01,  1.9505806e+01,
        6.8389760e+00,  1.8655851e+01, -5.7974410e+00, -3.3261300e-01,
        1.1959542e+01, -5.3809920e+00,  4.0166540e+00,  2.1500170e+00,
       -8.1602090e+00,  1.5615589e+01, -8.5334460e+00,  2.4121151e+01,
       -1.3265980e+00,  1.2399746e+01,  1.2886949e+01,  2.2285164e+01,
       -1.4165914e+01,  5.2192880e+00, -1.1874091e+01,  4.4301800e-01,
        1.4157402e+01, -1.1951283e+01,  1.1127334e+01, -1.6845198e+01,
       -2.0539934e+01,  1.2423321e+01, -1.5593609e+01,  1.5641645e+01,
      

In [24]:
# S-learner (example with Random Forest)

# mu_x
s_learner = RandomForestRegressor(max_depth=100, random_state=0)
s_learner.fit(X_W_train,Y_train)

# mu_0_hat
s_mu_0_hat = s_learner.predict(X_test_0)

# mu_1_hat
s_mu_1_hat = s_learner.predict(X_test_1)

# tau_hat
s_tau_hat = s_mu_1_hat - s_mu_0_hat
s_tau_hat


array([-1.11186490e-01,  9.12488780e-01,  6.35291860e-01, -6.52294800e-02,
        3.39102497e+00, -7.62303000e-02,  3.24262634e+00,  2.19018858e+00,
       -1.66160300e-02,  1.93644018e+00,  1.67133395e+00,  4.46759676e+00,
       -1.04766920e-01,  3.87377403e+00,  2.39904083e+00, -2.41835440e-01,
        1.71859432e+00,  9.00308330e-01,  3.26539507e+00,  3.72907600e-02,
        2.27679844e+00,  1.45526493e+00,  1.17403440e-01, -1.18852710e-01,
        5.09087300e-02,  1.33245133e+00,  3.84452000e-03,  6.56365900e-02,
       -3.11492700e-02,  3.98941770e-01, -4.18823500e-02,  2.26437270e-01,
        1.05709985e+00,  2.88076831e+00,  5.26323800e-02,  3.38004844e+00,
        1.48368591e+00,  2.13612616e+00,  8.28584000e-02, -1.49604030e-01,
        3.44477428e+00, -1.41905110e-01, -6.41165300e-02,  4.24053435e+00,
        1.77781256e+00,  6.50162350e-01,  9.54957290e-01,  5.30095200e-02,
       -1.29778380e-01,  3.43336600e-02,  1.66373123e+00,  2.63291267e+00,
        1.16536600e-01,  

In [25]:
# mean squared error
((s_tau_hat - tau_test)**2).mean()

19.92961697123671

# X-Learner

In [26]:
### X-Learner

# mu_0 (same procedure as for t-learner, maybe can speed up process)
x_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
x_learner_mu0.fit(X_train_control,Y_train_control)

# mu_1 (same procedure as for t-learner, maybe can speed up process)
x_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
x_learner_mu1.fit(X_train_treatment,Y_train_treatment)

# compute imputed treatment effect D_0 and D_1
# d_0
imputed_0 = x_learner_mu1.predict(X_train_control) - Y_train_control

# d_1
imputed_1 = Y_train_treatment - x_learner_mu0.predict(X_train_treatment)

# regress imputed on X
# tau_hat_0
x_tau_0_hat = RandomForestRegressor(max_depth=100, random_state=0)
x_tau_0_hat.fit(X_train_control ,imputed_0)

# tau_hat_1
x_tau_1_hat = RandomForestRegressor(max_depth=100, random_state=0)
x_tau_1_hat.fit(X_train_treatment ,imputed_1)

# estimate e_x to use as g_x
g_x_hat = RandomForestClassifier(max_depth=100, random_state=0)
g_x_hat.fit(X_train,W_train)
probabilities = g_x_hat.predict_proba(X_test)
probas_1 = probabilities[:,1]
probas_0 = probabilities[:,0]

# final estimator of tau
x_tau_hat = probas_1 * x_tau_0_hat.predict(X_test) + probas_0 * x_tau_1_hat.predict(X_test)
x_tau_hat


array([ 0.43573926,  7.13869407,  2.058598  , -1.03519091,  8.45635057,
       -1.74247355,  7.82848141,  8.94125078, -2.27321633,  8.78310729,
        8.17301583,  7.98444127, -1.29412274,  6.70087952,  8.75146621,
       -0.58025811,  5.48743568,  6.35202754,  5.22279138,  0.30936458,
        7.88673006,  6.22555636, -0.73468956, -2.24318394,  0.64245162,
        8.4506512 ,  0.57438311,  0.74447122,  5.06639044,  4.36565767,
        0.20555979, -0.17845122,  5.71797092,  7.10152182,  0.33441337,
        8.81707271,  8.4462502 ,  6.64608281,  1.85891287,  0.44380722,
        6.3527526 , -2.06530415, -0.24141579,  7.03943682,  7.21990218,
        7.44045433,  4.98532825,  0.16178542, -0.80081373, -0.09666842,
        8.40116338,  8.21942947,  0.22978846, -0.69555336,  0.27677599,
        8.02388447,  7.3491531 ,  0.5635289 , -1.20713063, -1.61884696,
        0.3748394 , -0.54920144, -1.58235699, -0.0511195 ,  6.10244778,
        6.63866547,  9.45066096, -0.31037158,  1.37121522,  7.51

In [27]:
# mean squared error (much lower here!)
((x_tau_hat - tau_test)**2).mean()

3.4816683120554544

# R-Learner

In [ ]:
### R-Learner


# DR-Learner

In [ ]:
### DR-Learner

# RA-Learner

In [28]:
### RA-Learner
# mu_0 (same procedure as for t-learner, maybe can speed up process)
ra_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
ra_learner_mu0.fit(X_train_control,Y_train_control)

# mu_1 (same procedure as for t-learner, maybe can speed up process)
ra_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
ra_learner_mu1.fit(X_train_treatment,Y_train_treatment)

# e_x
ra_learner_e_x = RandomForestClassifier(max_depth=100, random_state=0)
ra_learner_e_x.fit(X_train,W_train)

# ra-pseudo-outcome
ra_pseudo_outcome = W_train*(Y_train - ra_learner_mu0.predict(X_train)) + (1 - W_train)*(ra_learner_mu1.predict(X_train) - Y_train)

# tau_hat
ra_tau_hat_learner = RandomForestRegressor(max_depth=100, random_state=0)
ra_tau_hat_learner.fit(X_train, ra_pseudo_outcome)
ra_tau_hat = ra_tau_hat_learner.predict(X_test)
ra_tau_hat

array([-2.28161188,  6.02066492, -1.58451909, -1.48728227,  7.97174388,
       -1.55530114,  9.70251238,  8.56541138,  0.19841543,  7.87057793,
        6.51436103,  8.85509442, -1.80744622,  8.23009679,  8.70574753,
       -1.9622426 ,  8.14751857,  8.39434445,  7.56804023, -0.43261586,
        3.64468361,  8.24314236,  0.78449068, -2.45564832,  0.2870238 ,
        7.12943893, -3.05113083,  0.88594207, -1.34782782,  3.75168229,
        1.78220714,  7.61076713,  8.3037093 ,  8.70444658, -1.02192883,
        8.39508179,  7.64569233,  8.18773851, -2.76187507, -0.90967265,
        8.63754036, -1.32269311, -0.98227454, 10.67402515,  7.1997829 ,
        9.16943423,  4.30719467, -0.34055813,  0.25495792,  0.02485709,
        6.15093924,  7.13853292, -2.50364666, -4.79550179,  2.06059939,
        7.053132  ,  8.91657709,  1.6071043 , -0.11638196,  1.17592977,
        0.66009467,  0.97170252,  3.73838291,  4.00888578,  8.04377804,
        7.48197637,  5.83694368, -0.6055305 ,  1.80167406,  8.57

In [29]:
# mean squared error
((ra_tau_hat - tau_test)**2).mean()

4.069510087671737

# PW-Learner

In [38]:
### PW-Learner
# mu_0 (same procedure as for t-learner, maybe can speed up process)
pw_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
pw_learner_mu0.fit(X_train_control,Y_train_control)

# mu_1 (same procedure as for t-learner, maybe can speed up process)
pw_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
pw_learner_mu1.fit(X_train_treatment,Y_train_treatment)

# e_x
pw_learner_e_x = RandomForestClassifier(max_depth=100, random_state=0)
pw_learner_e_x.fit(X_train,W_train)

# ra-pseudo-outcome
pw_pseudo_outcome = (W_train/pw_learner_e_x.predict_proba(X_train)[:,1] - (1 - W_train)/(pw_learner_e_x.predict_proba(X_train)[:,0]))*Y_train

# tau_hat
pw_tau_hat_learner = RandomForestRegressor(max_depth=100, random_state=0)
pw_tau_hat_learner.fit(X_train, pw_pseudo_outcome)
pw_tau_hat = pw_tau_hat_learner.predict(X_test)
pw_tau_hat

array([ -3.67150662,   5.419136  ,   0.94982286,  -3.28634177,
         4.86787583,  11.33736869,   3.50511946,   6.85754421,
         0.48773564,   3.56184122,   3.98584062,   6.1161207 ,
         2.1680603 ,   0.83903379,   5.37940165,   2.69182192,
        11.4616472 ,   5.70688119,   8.90839601,  -1.16072023,
       -14.43996269,   9.04573602,   8.70059235,  -0.39594093,
        -0.13232457,   6.64276899,  -1.57363082,   1.7255159 ,
        -7.89203698,   9.96431029,   7.53165772,   9.11177779,
         4.76649214,   6.95006035,   3.68356441,   3.57486183,
         4.54836328,   2.16656738,  -2.7767068 ,  -2.10720239,
         4.50703044,  -0.81124343,   4.03822118,   2.3960783 ,
         3.82742502,   7.53816139,  -0.90215589,  -2.70849218,
         8.55452969,   2.93817745,   3.26498131,  -1.86139061,
        -3.56603143,   8.15577081,   7.82893862,   4.21095003,
         2.09605054,   2.85400296,  -1.07252858,   0.29413848,
         4.48873575,   1.29048471,   0.96693104,  10.76

In [39]:
# mean squared error
((pw_tau_hat - tau_test)**2).mean()

28.049428848330074

# F-Learner: AKA THE SAME AS PW-LEARNER!!!

In [40]:
### F-Learner
# mu_0 (same procedure as for t-learner, maybe can speed up process)
f_learner_mu0 = RandomForestRegressor(max_depth=100, random_state=0)
f_learner_mu0.fit(X_train_control,Y_train_control)

# mu_1 (same procedure as for t-learner, maybe can speed up process)
f_learner_mu1 = RandomForestRegressor(max_depth=100, random_state=0)
f_learner_mu1.fit(X_train_treatment,Y_train_treatment)

# e_x
f_learner_e_x = RandomForestClassifier(max_depth=100, random_state=0)
f_learner_e_x.fit(X_train,W_train)

# ra-pseudo-outcome
f_pseudo_outcome = (W_train/f_learner_e_x.predict_proba(X_train)[:,1] - (1 - W_train)/(f_learner_e_x.predict_proba(X_train)[:,0]))*Y_train

# tau_hat
f_tau_hat_learner = RandomForestRegressor(max_depth=100, random_state=0)
f_tau_hat_learner.fit(X_train, pw_pseudo_outcome)
f_tau_hat = f_tau_hat_learner.predict(X_test)
f_tau_hat

array([ -3.67150662,   5.419136  ,   0.94982286,  -3.28634177,
         4.86787583,  11.33736869,   3.50511946,   6.85754421,
         0.48773564,   3.56184122,   3.98584062,   6.1161207 ,
         2.1680603 ,   0.83903379,   5.37940165,   2.69182192,
        11.4616472 ,   5.70688119,   8.90839601,  -1.16072023,
       -14.43996269,   9.04573602,   8.70059235,  -0.39594093,
        -0.13232457,   6.64276899,  -1.57363082,   1.7255159 ,
        -7.89203698,   9.96431029,   7.53165772,   9.11177779,
         4.76649214,   6.95006035,   3.68356441,   3.57486183,
         4.54836328,   2.16656738,  -2.7767068 ,  -2.10720239,
         4.50703044,  -0.81124343,   4.03822118,   2.3960783 ,
         3.82742502,   7.53816139,  -0.90215589,  -2.70849218,
         8.55452969,   2.93817745,   3.26498131,  -1.86139061,
        -3.56603143,   8.15577081,   7.82893862,   4.21095003,
         2.09605054,   2.85400296,  -1.07252858,   0.29413848,
         4.48873575,   1.29048471,   0.96693104,  10.76

In [43]:
# mean squared error
print(((f_tau_hat - tau_test)**2).mean())
print("Same as for PW-Learner")

28.049428848330074
Same as for PW-Learner


# U-Learner

In [44]:
### U-Learner
# estimate e_x
u_learner_e_x = RandomForestClassifier(max_depth=100, random_state=0)
u_learner_e_x.fit(X_train,W_train)

# estimate mu_x
u_learner_mu_x = RandomForestRegressor(max_depth=100, random_state=0)
u_learner_mu_x.fit(X_train,Y_train)

# compute residuals
u_learner_residuals = (Y_train - u_learner_mu_x.predict(X_train))/(W_train - u_learner_e_x.predict_proba(X_train)[:,1])

# tau_hat - regress residuals on X
u_tau_hat_learner = RandomForestRegressor(max_depth=100, random_state=0)
u_tau_hat_learner.fit(X_train,u_learner_residuals)

u_tau_hats = u_tau_hat_learner.predict(X_test)
u_tau_hats


array([ -7.27584219,   3.95474479,  -2.84586592,  -3.47356286,
         9.58491752,  -1.29113952,   9.10377518,   7.371955  ,
         0.87990968,   8.66787192,   6.74418826,   9.65057379,
        -2.2139789 ,   6.74003883,   6.87477109,  -0.31512856,
        11.47117927,   9.07102477,   7.09915715,  -0.81143   ,
         4.22507164,  10.12674094,   2.79494082,  -4.4350147 ,
         3.73758946,   4.04496471, -10.27548073,   3.34067231,
        -5.6807958 ,   5.81985705,   0.90010233,   3.68227803,
         6.51852169,   7.43257051,  -4.04116439,   5.89907792,
         8.62949841,   6.63454351,  -6.9165867 ,  -0.22001141,
         5.85681604,  -2.47248343,  -2.17392948,  18.22181652,
         7.48444115,  11.03531917,   3.34357131,  -0.64783393,
         3.47714749,   0.89829138,   5.3346247 ,   7.44624711,
        -1.76205008,  -4.53871612,  -3.23491375,   6.51296849,
         5.28758697,   4.62896903,  -0.60930052,   5.51134862,
         3.85775834,   3.12604054,   5.50673867,   4.68

In [45]:
# mean squared error
((u_tau_hats - tau_test)**2).mean()

14.504422072647406

# Just some lasso tests

In [87]:
from sklearn.preprocessing import PolynomialFeatures
poly_train = PolynomialFeatures(degree=4, interaction_only=False, include_bias=False)
X_poly_train = poly_train.fit_transform(X_train)
poly_test = PolynomialFeatures(degree=4, interaction_only=False, include_bias=False)
X_poly_test = poly_test.fit_transform(X_test)
X_poly_train

array([[-7.36680000e-01, -2.62747000e-01,  3.23882000e-01, ...,
         5.24342131e-02, -5.73156988e-02,  6.26516378e-02],
       [-1.04073500e+00,  3.76025000e-01, -2.85208000e-01, ...,
         5.39948598e-01, -1.31151971e+00,  3.18564389e+00],
       [ 4.43016000e-01, -6.36760000e-01,  5.13939000e-01, ...,
         1.56482356e+00, -1.66762945e+00,  1.77718949e+00],
       ...,
       [ 9.69699000e-01,  3.69004000e-01, -6.65190000e-01, ...,
         3.00178243e-04, -1.90775263e-02,  1.21245300e+00],
       [-3.71236000e-01,  4.38290000e-01, -3.80551000e-01, ...,
         1.36929802e-04,  1.07574016e-03,  8.45116903e-03],
       [ 7.29611000e-01,  6.70044000e-01, -1.66766700e+00, ...,
         3.67231506e-03,  1.81730813e-04,  8.99326113e-06]])

In [88]:
from sklearn.linear_model import Lasso, LassoCV
lasso_poly = LassoCV(cv=10, random_state=0, tol=1e-2)

In [89]:
import time

t0 = time.time()
lasso_poly.fit(X_poly_train,Y_train)

t1 = time.time()

total = t1-t0
print(f"{total:.4f} seconds")

92.5842 seconds


In [ ]:
# degree 3: 10 seconds to fit (100% cpu)
# degree 4: 90 seconds to fit (100% cpu)

In [91]:
y_predictions = lasso_poly.predict(X_poly_test)

In [92]:
((y_predictions - Y_test)**2).mean()

14.236306434483982