In [3]:
import numpy as np
import jsonpickle
import seaborn as sns

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results.json"
f = open(file_name, 'r')
json_str = f.read()
results_all = jsonpickle.decode(json_str)

In [ ]:
# S-Learner best, X_learner good, T, DR, RA, also good, only PW-bad
# almost same as one, PW also good?
# X-learner best, S-learner worst (PW actually worst, but extreme)
# X-learner best, DR/PW also good, rest oke (PW very bad)
# T-learner best?, R/RA very good
# X-learner best, but S/T/DR/RA all very good
# S-learner best, then X-learner
# S-learner best,
# X-learner best, (especially for RF)
# X-learner best,
# T-learner best
# S-learner best?, T/X/DR/RA all very good
# S-learner best, X also very good
# S-learner best, X also very good, R bad
# X-learner best, DR-learner also very good
# X-learner best, DR/RA good but then at siz=5000 bad?
# DR/RA best, X also very good
# S-learner best ??? probably because the cates are not scaled enough
# S-learner best
# S-learner best
# X best, DR/RA very good
# X best, DR/RA very good,
# X best, but all perform a bit bad
# T, S, X R DR all good, probably because of not scalling

In [ ]:
# CONCLUSIONS
# -----------

# 1: If zero cate --> S-learner is the best, X-learner also performs good
# 2: If simple cate --> X-learner is the best, often DR/RA/R learner also perform good
# 3: if complex cate --> T very good, somehow S-learner also good (probably to bad scalling of outcomes), DR/RA/R learner also good
# 4: PW learner very bad mostly, U-learner also not good

# Base learners
# -------------
# RF and Linear model seem to be more stable than Neural Network, at least with these hyperparameters.
# All "pseudo-outome" metalearners very bad with Neural Network??? --> probably the classification task is bad

12 setups

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_12_setups_no_cv.json"
f = open(file_name, 'r')
json_str = f.read()
results_12 = jsonpickle.decode(json_str)

In [ ]:
results_12[11][0]

In [ ]:
# S-learner best
# S learner best
# X-learner best, DR/RA very good
# X-learner best, DR/RA very good, S bad
# R learner best
# S-learner best--> because most Ys are near zero!!!, else, DR/RA very good and also X/T learner


# CONCLUSION
# looks to make sense, PW is bad



In [ ]:
# open
# LOAD JSON FILE
file_name = "check_repro.json"
f = open(file_name, 'r')
json_str = f.read()
check = jsonpickle.decode(json_str)

In [ ]:
check[1][0]

with cross-fitting

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_12_setups.json"
f = open(file_name, 'r')
json_str = f.read()
results_cf = jsonpickle.decode(json_str)

In [ ]:
results_cf[11][2]

In [ ]:
# OK nice

# much better with cross-fitting now!!

IHDP

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results = jsonpickle.decode(json_str)

In [ ]:
ihdp_results[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross[2]

In [ ]:
# better than cross-fitting

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross_.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross_ = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross_[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross_.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross_ = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross_[0]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-0.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_1 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_1[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-4.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_4 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_4[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-2.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_2 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_2[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-3.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_3 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_3[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_setup_2_old.json"
f = open(file_name, 'r')
json_str = f.read()
data = jsonpickle.decode(json_str)

In [ ]:
metalearner_names = ['T-Learner', 'S-Learner', 'X-Learner', 'R-Leaner', 'DR-Learner', 'RA-Leaner', 'PW-Leaner',
                     'U-Learner']
metalearner_names = np.repeat(metalearner_names, 40)
metalearner_names = np.tile(metalearner_names, 3)
metalearner_names = np.array(metalearner_names)[:, np.newaxis]

In [ ]:
baselearner_names = ["random forest", "linear models", "neural network"]
baselearner_names = np.repeat(baselearner_names, 320)
baselearner_names = np.array(baselearner_names)[:, np.newaxis]
baselearner_names

In [ ]:
sample_sizes = np.tile([500, 1000, 2000, 5000], 240)[:, np.newaxis]
sample_sizes

In [ ]:
# using dictionary to convert specific columns
convert_dict = {'mse': float,
                'size': int,
                'metalearner': 'category',
                'baselearner': 'category'
                }
data = data.astype(convert_dict)

HERE!!!

In [ ]:
def process_data_plot(results):
    # flatten and concatenate results
    rf_results = np.sqrt(results[0].flatten('F')[:, np.newaxis])
    lm_results = np.sqrt(results[1].flatten('F')[:, np.newaxis])
    nn_results = np.sqrt(results[2].flatten('F')[:, np.newaxis])
    all_results = np.concatenate((rf_results, lm_results, nn_results))
    # add names
    metalearner_names = ['T-Learner', 'S-Learner', 'X-Learner', 'R-Leaner', 'DR-Learner', 'RA-Leaner', 'PW-Leaner',
                         'U-Learner']
    metalearner_names = np.repeat(metalearner_names, 40)
    metalearner_names = np.tile(metalearner_names, 3)
    metalearner_names = np.array(metalearner_names)[:, np.newaxis]
    baselearner_names = ["random forest", "linear models", "neural network"]
    baselearner_names = np.repeat(baselearner_names, 320)
    baselearner_names = np.array(baselearner_names)[:, np.newaxis]
    # sample sizes
    sample_sizes = np.tile([500, 1000, 2000, 5000], 240)[:, np.newaxis]
    # concatenate all
    data = np.concatenate((all_results, sample_sizes, metalearner_names, baselearner_names), axis=1)
    data = pd.DataFrame(data)
    # add column name and specify data type
    data.columns = ['mse', 'size', 'metalearner', 'baselearner']
    convert_dict = {'mse': float,
                    'size': int,
                    'metalearner': 'category',
                    'baselearner': 'category'
                    }
    data = data.astype(convert_dict)
    return data


In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_experiment/results_setup_11.json"
f = open(file_name, 'r')
json_str = f.read()
data = jsonpickle.decode(json_str)

In [ ]:
data = process_data_plot(data)
data

In [ ]:
hue_order = ["T-Learner", "S-Learner", "X-Learner", "R-Leaner", "DR-Learner", "RA-Leaner", "PW-Leaner",
             "U-Learner"]
col_order = ["random forest", "linear models", "neural network"]
sns.set_style("whitegrid")

In [ ]:
g = sns.FacetGrid(data, col="baselearner", sharey=False,
                  col_order=col_order)
g.map(sns.lineplot, "size", "mse", "metalearner", errorbar=None, estimator="mean", marker="o", hue_order=hue_order)
g.set_axis_labels("sample size", "Mean RMSE")
g.set_titles(col_template=" base learner = {col_name} ")
g.add_legend()

In [ ]:
# setup 6, neural network ?? why S-learner so good, but lienar models so bad
# setup 7 so bad
# setup 8 so bad U learner

exlcude pw and u learner

In [ ]:
mask = data['metalearner'].isin(['PWLearner', 'U-Learner'])
data_exclude = data[~mask]
hue_order_exclude = ["T-Learner", "S-Learner", "X-Learner", "R-Leaner", "DR-Learner", "RA-Leaner"]

In [ ]:
g = sns.FacetGrid(data_exclude, col="baselearner", sharey=False,
                  col_order=col_order)
g.map(sns.lineplot, "size", "mse", "metalearner", errorbar=None, estimator="mean", marker="o",
      hue_order=hue_order_exclude, linewidth=0.75)
g.set_axis_labels("sample size", "Mean RMSE")
g.set_titles(col_template=" base learner = {col_name} ")
g.add_legend()

In [ ]:
g.savefig("LOOKHERE.png", dpi=1200)

In [ ]:
# 1: ok
# 2: ok
# 3: ok
# 4: ok
# 5: ok
# 6: ?, but in künzel paper the same outcome --> t/s learner no big difference: BUT in linear models they have!!
# 7: ok, --> baselearner matters! --> R-RF worst but, R-LM well!
# 8: ok, same as 7
# 9: oke, RA seems to perform bad in unbalanced settings
# 10: oke
# 11: oke
# 12: oke
# 13: oke
#





end

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results.json"
f = open(file_name, 'r')
json_str = f.read()
results_all = jsonpickle.decode(json_str)

In [ ]:
results_all[0][0]

In [ ]:
# S-Learner best, X_learner good, T, DR, RA, also good, only PW-bad
# almost same as one, PW also good?
# X-learner best, S-learner worst (PW actually worst, but extreme)
# X-learner best, DR/PW also good, rest oke (PW very bad)
# T-learner best?, R/RA very good
# X-learner best, but S/T/DR/RA all very good
# S-learner best, then X-learner
# S-learner best,
# X-learner best, (especially for RF)
# X-learner best,
# T-learner best
# S-learner best?, T/X/DR/RA all very good
# S-learner best, X also very good
# S-learner best, X also very good, R bad
# X-learner best, DR-learner also very good
# X-learner best, DR/RA good but then at siz=5000 bad?
# DR/RA best, X also very good
# S-learner best ??? probably because the cates are not scaled enough
# S-learner best
# S-learner best
# X best, DR/RA very good
# X best, DR/RA very good,
# X best, but all perform a bit bad
# T, S, X R DR all good, probably because of not scalling

In [ ]:
# CONCLUSIONS
# -----------

# 1: If zero cate --> S-learner is the best, X-learner also performs good
# 2: If simple cate --> X-learner is the best, often DR/RA/R learner also perform good
# 3: if complex cate --> T very good, somehow S-learner also good (probably to bad scalling of outcomes), DR/RA/R learner also good
# 4: PW learner very bad mostly, U-learner also not good

# Base learners
# -------------
# RF and Linear model seem to be more stable than Neural Network, at least with these hyperparameters.
# All "pseudo-outome" metalearners very bad with Neural Network??? --> probably the classification task is bad

12 setups

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_12_setups_no_cv.json"
f = open(file_name, 'r')
json_str = f.read()
results_12 = jsonpickle.decode(json_str)

In [ ]:
results_12[11][0]

In [ ]:
# S-learner best
# S learner best
# X-learner best, DR/RA very good
# X-learner best, DR/RA very good, S bad
# R learner best
# S-learner best--> because most Ys are near zero!!!, else, DR/RA very good and also X/T learner


# CONCLUSION
# looks to make sense, PW is bad



In [ ]:
# open
# LOAD JSON FILE
file_name = "check_repro.json"
f = open(file_name, 'r')
json_str = f.read()
check = jsonpickle.decode(json_str)

In [ ]:
check[1][0]

with cross-fitting

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_12_setups.json"
f = open(file_name, 'r')
json_str = f.read()
results_cf = jsonpickle.decode(json_str)

In [ ]:
results_cf[11][2]

In [ ]:
# OK nice
# much better with cross-fitting now!!

IHDP

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results = jsonpickle.decode(json_str)

In [ ]:
ihdp_results[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross[2]

In [ ]:
# better than cross-fitting

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross_.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross_ = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross_[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "results_ihdp_no_cross_.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_no_cross_ = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_no_cross_[0]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-0.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_1 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_1[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-4.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_4 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_4[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-2.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_2 = jsonpickle.decode(json_str)

In [ ]:
ihdp_results_2[2]

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_ihdp_1e-3.json"
f = open(file_name, 'r')
json_str = f.read()
ihdp_results_3 = jsonpickle.decode(json_str)

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_setup_1_old.json"
f = open(file_name, 'r')
json_str = f.read()
results_1 = jsonpickle.decode(json_str)

In [ ]:
rf_results = results_1[0].flatten('F')[:, np.newaxis]
lm_results = results_1[1].flatten('F')[:, np.newaxis]
nn_results = results_1[2].flatten('F')[:, np.newaxis]

In [ ]:
all_results = np.concatenate((rf_results, lm_results, nn_results))
all_results

In [ ]:
metalearner_names = ['T-Learner', 'S-Learner', 'X-Learner', 'R-Leaner', 'DR-Learner', 'RA-Leaner', 'PW-Leaner',
                     'U-Learner']

In [ ]:
metalearner_names = np.repeat(metalearner_names, 40)
metalearner_names = np.tile(metalearner_names, 3)

In [ ]:
metalearner_names

In [ ]:
metas = np.array(metalearner_names)[:, np.newaxis]

In [ ]:
metas

In [ ]:
first_plot = sns.lineplot(data=data, x="size", y="mse", hue="metalearner", estimator="mean", errorbar=None, marker='o')

In [ ]:
hue_order = ["T-Learner", "S-Learner", "X-Learner", "R-Leaner", "DR-Learner", "RA-Leaner", "PW-Leaner",
             "U-Learner"]
col_order = ["random forest", "linear models", "neural network"]
sns.set_style("whitegrid")

In [ ]:
g = sns.FacetGrid(data, col="baselearner", sharey=False,
                  col_order=col_order)
g.map(sns.lineplot, "size", "mse", "metalearner", errorbar=None, estimator="mean", marker="o", hue_order=hue_order)
g.set_axis_labels("sample size", "Mean MSE")
g.set_titles(col_template=" base learner = {col_name} ")
g.add_legend()

In [ ]:
g.savefig("color_bright.png", dpi=1200)

In [ ]:
g.savefig("first_setup.eps", format='eps')  # for latex

In [ ]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/Documents/Master Thesis ETH/DataSets /Generated/simulated_data_large.json"
f = open(file_name, 'r')
json_str = f.read()
large_simulation = jsonpickle.decode(json_str)

In [ ]:
large_simulation[17][0][3][0]

In [ ]:
dim1 = 24
dim2 = 10
dim3 = 4
dim4 = 2

empty_list = [[[[[] for _ in range(dim4)] for _ in range(dim3)] for _ in range(dim2)] for _ in range(dim1)]
empty_list

In [ ]:
empty_list[20][0][0][0]

In [ ]:
empty_list

In [ ]:
data = []
for i in range(dim1):
    data.append([])

for i in range(dim1):
    for r in range(dim2):
        data[i].append([])

for i in range(dim1):
    for r in range(dim2):
        for s in range(dim3):
            data[i][r].append([])

for i in range(dim1):
    for r in range(dim2):
        for s in range(dim3):
            for t in range(dim3):
                data[i][r][s].append([])

In [ ]:
data[0][0][0][0] = 3

In [ ]:
data == empty_list

In [ ]:
s = [500, 1000, 200, 300]
len(s)

In [ ]:
lel = [[], []]
lel = 1, 3
lel[1]

In [ ]:
sizes = [100, 1000, 200, 400]
for s, size in enumerate(sizes):
    print(s, ",", size)

In [ ]:
import scipy

scipy.__version__

In [ ]:
import scipy

scipy.__version__

In [ ]:
pip
list

In [ ]:
import scipy

scipy.__version__

In [14]:
# open
# LOAD JSON FILE
file_name = "results_setting_1_runs_1.json"
f = open(file_name, 'r')
json_str = f.read()
res = jsonpickle.decode(json_str)

In [19]:
res[1]

array([[ 2.45827304,  0.16137142,  2.27082726,  0.61352291,  2.91958928,
         2.41761605, 14.18158114,  0.61342217]])

In [ ]:
# 0.317731,0.031008,0.124688,0.18466,0.254088,0.195822,0.79867,0.182264


In [25]:
x = 3.0

In [26]:
type(x)

float

In [31]:
import configargparse

In [32]:
def check(number):
    if type(number) is not int:
        raise configargparse.ArgumentTypeError("The number has to an integer")
    if number <= 0:
        raise configargparse.ArgumentTypeError("The number has to be positive")
    return number

In [ ]:
# LARGE

compare sample sizes

In [43]:
import pandas as pd

In [50]:
sizes = np.tile([500, 1000, 2000, 5000], 10)
sizes_big = np.tile([1000, 2000, 5000, 10000], 10)


In [52]:
sizes, sizes_big

(array([ 500, 1000, 2000, 5000,  500, 1000, 2000, 5000,  500, 1000, 2000,
        5000,  500, 1000, 2000, 5000,  500, 1000, 2000, 5000,  500, 1000,
        2000, 5000,  500, 1000, 2000, 5000,  500, 1000, 2000, 5000,  500,
        1000, 2000, 5000,  500, 1000, 2000, 5000]),
 array([ 1000,  2000,  5000, 10000,  1000,  2000,  5000, 10000,  1000,
         2000,  5000, 10000,  1000,  2000,  5000, 10000,  1000,  2000,
         5000, 10000,  1000,  2000,  5000, 10000,  1000,  2000,  5000,
        10000,  1000,  2000,  5000, 10000,  1000,  2000,  5000, 10000,
         1000,  2000,  5000, 10000]))

In [60]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_setup_1_large.json"
f = open(file_name, 'r')
json_str = f.read()
large = jsonpickle.decode(json_str)

In [65]:
large[0]

array([[4.22589395e-01, 6.31128936e-04, 1.25427872e-01, 5.08952100e-01,
        2.80774561e-01, 2.72178565e-01, 7.86113832e+00, 5.28084582e-01],
       [3.54742681e-01, 4.16250690e-04, 1.12486278e-01, 6.47029166e-01,
        2.61015229e-01, 2.51185802e-01, 5.58346526e+00, 8.27471562e-01],
       [1.97886199e-01, 5.40596895e-04, 6.55942352e-02, 2.56601572e-01,
        1.17420271e-01, 1.12276953e-01, 3.15809750e+00, 2.85931547e-01],
       [1.41920142e-01, 4.38237045e-04, 5.18716055e-02, 1.72899215e-01,
        8.17216522e-02, 7.68210037e-02, 2.96111677e+00, 1.85506850e-01],
       [2.00366478e-01, 7.74687762e-04, 9.93928009e-02, 4.32715761e-01,
        1.72631333e-01, 1.66110458e-01, 2.87825358e+00, 5.22854453e-01],
       [1.97104797e-01, 1.10675031e-03, 7.27878633e-02, 3.26303098e-01,
        1.37398904e-01, 1.27859504e-01, 2.31776062e+00, 3.35230304e-01],
       [1.64466338e-01, 1.12718693e-03, 6.03636882e-02, 2.48708965e-01,
        1.13907069e-01, 1.08912780e-01, 1.79163057e+00, 2.

In [72]:
large_ = pd.DataFrame(large[0])
large_.describe()

0          1          2          3          4          5  \
count  40.000000  40.000000  40.000000  40.000000  40.000000  40.000000   
mean    0.239719   0.001207   0.086635   0.330018   0.155718   0.150148   
std     0.104356   0.000766   0.038129   0.140897   0.072758   0.073283   
min     0.116150   0.000416   0.041303   0.159878   0.078230   0.073299   
25%     0.168827   0.000809   0.055650   0.197477   0.100155   0.096196   
50%     0.199126   0.001036   0.078988   0.317191   0.136186   0.126676   
75%     0.326915   0.001347   0.109130   0.400071   0.192752   0.183114   
max     0.616472   0.004212   0.223411   0.680393   0.410571   0.417321   

               6          7  
count  40.000000  40.000000  
mean    3.386605   0.369180  
std     2.087418   0.172720  
min     0.839530   0.166059  
25%     1.850522   0.218512  
50%     2.912971   0.336044  
75%     4.240060   0.440900  
max    10.950940   0.827472

In [21]:
# open
# LOAD JSON FILE
file_name = "/Users/arberimbibaj/results_experiment/results_setup_1.json"
f = open(file_name, 'r')
json_str = f.read()
small = jsonpickle.decode(json_str)

In [22]:
small_ = pd.DataFrame(small[0])
small_.describe()

0          1          2          3          4          5  \
count  40.000000  40.000000  40.000000  40.000000  40.000000  40.000000   
mean    0.298261   0.001499   0.102183   0.440094   0.199617   0.191154   
std     0.117970   0.000969   0.036046   0.186114   0.089511   0.087244   
min     0.164589   0.000416   0.063595   0.216792   0.108433   0.104222   
25%     0.205064   0.000920   0.073833   0.295140   0.134761   0.129494   
50%     0.272573   0.001299   0.091551   0.409765   0.168387   0.164617   
75%     0.386644   0.001793   0.119672   0.527218   0.235353   0.219130   
max     0.661787   0.004861   0.220363   1.000114   0.476754   0.450104   

               6          7  
count  40.000000  40.000000  
mean    4.409676   0.491970  
std     2.131921   0.220583  
min     0.898780   0.225723  
25%     3.098204   0.323095  
50%     4.146450   0.448019  
75%     5.370927   0.566968  
max    10.245620   1.152708

In [39]:
np.concatenate((small[0], np.tile([100], reps=40)[:, np.newaxis]), axis=1)

array([[6.13583108e-01, 5.54602297e-04, 1.82868607e-01, 1.00011383e+00,
        4.76754053e-01, 4.50104438e-01, 6.67434047e+00, 1.15270770e+00,
        1.00000000e+02],
       [3.85600669e-01, 4.16048480e-04, 1.31930708e-01, 4.38974988e-01,
        2.25667604e-01, 2.10073665e-01, 4.62321334e+00, 5.41324898e-01,
        1.00000000e+02],
       [4.22244842e-01, 4.83003359e-04, 1.17908786e-01, 4.30848594e-01,
        2.12756775e-01, 2.01435301e-01, 4.46106534e+00, 5.58289852e-01,
        1.00000000e+02],
       [2.71518018e-01, 6.75513951e-04, 8.45354460e-02, 2.87783588e-01,
        1.56723154e-01, 1.49079769e-01, 3.90306137e+00, 3.01149892e-01,
        1.00000000e+02],
       [3.89773790e-01, 1.08691918e-03, 1.25594871e-01, 5.93368111e-01,
        2.90643601e-01, 2.96395635e-01, 2.73435094e+00, 5.87191767e-01,
        1.00000000e+02],
       [3.01891890e-01, 4.56830797e-03, 1.30438913e-01, 4.61834215e-01,
        2.47180049e-01, 2.40001284e-01, 3.03369236e+00, 5.56489551e-01,
        1.0

In [40]:
# SMALL

In [5]:
lel = np.array([[2,4,5,3,1],[2,4,5,3,1]])
lel

array([[2, 4, 5, 3, 1],
       [2, 4, 5, 3, 1]])

In [6]:
size = 100

In [14]:
np.concatenate((lel[0, :], np.array([100])), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [19]:
np.array([100])[:, np.newaxis].shape

(1, 1)

In [20]:
lel[0, :].shape

(5,)

In [40]:
# open
# LOAD JSON FILE
file_name = "results_simulated_setting1_1run(s).json"
f = open(file_name, 'r')
json_str = f.read()
with_sizes = jsonpickle.decode(json_str)

In [43]:
with_sizes[2]

array([[1.27533510e+00, 3.17329919e-02, 1.05796466e+00, 1.38017194e+00,
        1.13561290e+00, 1.77285295e+00, 5.76785698e+00, 2.61190515e+00,
        5.00000000e+01],
       [7.32655238e-01, 1.02838449e-01, 6.03403846e-01, 1.10197551e+00,
        5.07274411e-01, 7.62102739e-01, 4.47366445e+00, 1.21643906e+01,
        1.00000000e+02],
       [8.44374992e-01, 8.49113345e-03, 7.02883533e-01, 7.92215750e-01,
        9.93697603e-01, 1.02193699e+00, 6.71089467e+00, 4.96652678e+00,
        2.00000000e+02]])