In [1]:
from MetaLearner import *

In [2]:
import pickle
import numpy as np
import time

In [3]:
# todo: https://stackoverflow.com/questions/24168569/how-to-add-names-to-a-numpy-array-without-changing-its-dimension

In [4]:
# This file runs the experiment

In [5]:
tf.keras.backend.set_floatx('float64')

In [6]:
tf.keras.utils.set_random_seed(8953)

In [7]:
file_name = "/Users/arberimbibaj/Documents/Master Thesis ETH/DataSets /Generated/data_synthetic_one_run.pkl"
open_file = open(file_name, "rb")
data = pickle.load(open_file)
open_file.close()

In [8]:
n_setups = 1
# sample_sizes = [500, 1000, 2000, 5000]
sample_sizes = [500, 1000, 2000, 5000]
n_runs = 1

In [9]:
learners = [TLearner('rf'), SLearner('rf'), XLearner('rf'), RLearner('rf'), DRLearner('rf'), RALearner('rf'),
            PWLearner('rf'), ULearner('rf'),
            TLearner('lasso'), SLearner('lasso'), XLearner('lasso'), RLearner('lasso'), DRLearner('lasso'),
            RALearner('lasso'), PWLearner('lasso'), ULearner('lasso'),
            TLearner('nn'), SLearner('nn'), XLearner('nn'), RLearner('nn'), DRLearner('nn'), RALearner('nn'),
            PWLearner('nn'), ULearner('nn')]

In [ ]:
learners = [TLearner('nn'), SLearner('nn'), XLearner('nn'), RLearner('nn'), DRLearner('nn'), RALearner('nn'),
            PWLearner('nn'), ULearner('nn')]

In [ ]:
learners = [TLearner('nn')]

In [ ]:
# What we want: For each setting and base learner --> matrix which includes the MSE, columns: Metalearners + SampleSize, rows: Run(1-10)
# --> So we can plot the mean and 1se of the MSE for each Metalearner, each samplesize; giving the setting and baselearner
# --> number of plots: settings*baselearner.

In [10]:
results = []

for i in range(n_setups):
    results.append([])

for i in range(n_setups):
    for baselearner in range(3):
        results[i].append([])

results

[[[], [], []]]

In [11]:
dim = data[0][0][0][0].shape[1]  # dimension of x


# helper function to get y, x, w, tau, out of data[][][][]
def get_variables(dataset, setup, samplesize, run, train_test):
    y = dataset[setup][samplesize][run][train_test][:, 0]
    x = dataset[setup][samplesize][run][train_test][:, 1:(dim - 2)]
    w = dataset[setup][samplesize][run][train_test][:, (dim - 2)]
    tau = dataset[setup][samplesize][run][train_test][:, (dim - 1)]
    return y, x, w, tau

In [12]:
b = 0
m = 0
s = 0

for i in range(n_setups):
    print(f'Setup: {i + 1}')
    # array for all mses for one setup
    setup_mse = np.empty(shape=(0, 24))
    s = 0  # restart index for samplesize
    for size in sample_sizes:
        print(f'Sample Size: {s + 1}')
        # array for all mses for one setup and samplesize.
        size_mse = np.empty(shape=(0, 24))
        for r in range(n_runs):
            print(f'Run: {r + 1}')
            # array for all mses in one setup, samplesize and run.
            mses = np.empty(shape=(1, 24))
            # get data for specific setup, samplesize and run.
            temp_y_train, temp_x_train, temp_w_train, temp_tau_train = get_variables(dataset=data, setup=i,
                                                                                     samplesize=s, run=r,
                                                                                     train_test=0)
            temp_y_test, temp_x_test, temp_w_test, temp_tau_test = get_variables(dataset=data, setup=i,
                                                                                 samplesize=s, run=r,
                                                                                 train_test=1)
            # restart index for metalearner
            m = 0
            for l in learners:
                if m % 8 == 0: print(f'BaseLearner')
                print(f'Learner {m + 1}: {l}')
                tic = time.time()
                # training and testing MetaLearner.
                learner = l
                learner.fit(temp_x_train, temp_y_train, temp_w_train)
                predictions = learner.predict(temp_x_test)
                temp_mse = ((predictions - temp_tau_test) ** 2).mean()
                # append mse of specific metalearner to 'mses'.
                mses[0, m] = temp_mse
                # print time
                toc = time.time()
                print(f'Time: {round(toc - tic, 4)} seconds.')
                # update index
                m += 1
            # append 'mses' to 'size_mse'.
            size_mse = np.append(size_mse, mses, axis=0)
        # append 'size_mse' to 'setup_mse'.
        setup_mse = np.append(setup_mse, size_mse, axis=0)
        # update index
        s += 1
    # append to results
    results[i][0] = setup_mse[:, 0:8]  # random forest
    results[i][1] = setup_mse[:, 8:16]  # lasso
    results[i][2] = setup_mse[:, 16:24]  # neural network





# this should make sense i guess! :)
# TODO: CHECK IF IT MAKES IT FASTER IF EVERYTHING IS EITHER IN NP OR IN LIST/ARRAY BASE PYTHON.
# TODO: DONE :)
# TODO: DONE :)
# TODO: DONE :)

### IT TOOK 6M 40S FOR --> SAMPLE SIZES [200, 200], TEST SIZE = 50, 2 SETUPS, 2 RUNS LOL

### 35min for all Baselearners, 1 Setup, 1 Run, 4 Sample Sizes  ()

Setup: 1
Sample Size: 1
Run: 1
BaseLearner
Learner 1: <MetaLearner.TLearner object at 0x290501960>
Time: 1.6043 seconds.
Learner 2: <MetaLearner.SLearner object at 0x290559360>
Time: 2.9222 seconds.
Learner 3: <MetaLearner.XLearner object at 0x290558c10>
Time: 6.9985 seconds.
Learner 4: <MetaLearner.RLearner object at 0x290559fc0>
Time: 8.6622 seconds.
Learner 5: <MetaLearner.DRLearner object at 0x29055a650>
Time: 8.0751 seconds.
Learner 6: <MetaLearner.RALearner object at 0x290559840>
Time: 6.7964 seconds.
Learner 7: <MetaLearner.PWLearner object at 0x290559ba0>
Time: 5.53 seconds.
Learner 8: <MetaLearner.ULearner object at 0x290559a80>
Time: 8.84 seconds.
BaseLearner
Learner 9: <MetaLearner.TLearner object at 0x29055a4a0>
Time: 1.759 seconds.
Learner 10: <MetaLearner.SLearner object at 0x29055a050>
Time: 1.8999 seconds.
Learner 11: <MetaLearner.XLearner object at 0x290559e70>
Time: 3.7884 seconds.
Learner 12: <MetaLearner.RLearner object at 0x290559f90>
Time: 4.5362 seconds.
Learner 

In [ ]:
### Training tau0 and tau1 takes extemely long!! compared to mu0 and mu1 in lasso!!! probably because of the max_iter

In [16]:
setup_mse

array([[2.16444470e+00, 4.27842608e-03, 9.21012022e-01, 3.66025159e+00,
        1.53230589e+00, 1.52415069e+00, 4.09339720e+00, 4.73376558e+00,
        2.30856836e+00, 1.00444203e+00, 1.52648324e+00, 2.81551860e-02,
        2.15632829e+00, 2.11505993e+00, 3.60900826e-02, 3.37949930e-02,
        6.94569409e-01, 1.67760106e-01, 5.67150213e-01, 2.99783242e+00,
        4.67543002e-01, 9.44197332e-01, 1.67171112e+01, 1.27092459e+01],
       [3.45344301e+00, 4.39522035e-03, 8.98048803e-01, 4.66712618e+00,
        1.99804106e+00, 2.07228875e+00, 1.11219752e+01, 5.06884773e+00,
        1.79140523e+00, 1.19394656e+00, 1.26001859e+00, 4.47374476e-02,
        3.23602393e-01, 1.58885352e+00, 5.30864073e+00, 4.23107428e-02,
        6.10677966e-01, 1.87881437e-01, 7.59496834e-01, 2.28749562e+01,
        6.02121307e+00, 1.13773604e+00, 5.87168478e+01, 1.73414317e+03],
       [2.23366163e+00, 6.84383109e-03, 7.10761628e-01, 4.10779691e+00,
        1.64412098e+00, 1.57652122e+00, 1.42685732e+01, 4.7189

In [ ]:
# set n_trees to 1000 to gain time or maybe even 500

In [25]:
results[0][2]

array([[6.94569409e-01, 1.67760106e-01, 5.67150213e-01, 2.99783242e+00,
        4.67543002e-01, 9.44197332e-01, 1.67171112e+01, 1.27092459e+01],
       [6.10677966e-01, 1.87881437e-01, 7.59496834e-01, 2.28749562e+01,
        6.02121307e+00, 1.13773604e+00, 5.87168478e+01, 1.73414317e+03],
       [8.64564998e-01, 1.83118181e-01, 7.93892399e-01, 7.91985926e+00,
        1.08008490e+01, 1.03588484e+00, 7.24271615e+01, 3.43769983e+02],
       [2.33476356e-01, 7.44663407e-02, 3.66871969e-01, 3.13555839e+00,
        3.48196634e+01, 4.73894650e-01, 1.24064119e+02, 1.85033123e+03]])

In [ ]:
# Look oke, NN looks a bit unstable!

In [ ]:
# results[0][2]
# 0.694569,0.167760,0.567150,2.997832,0.467543,0.944197,16.717111,12.709246
# 0.610678,0.187881,0.759497,22.874956,6.021213,1.137736,58.716848,1734.143168
# 0.864565,0.183118,0.793892,7.919859,10.800849,1.035885,72.427161,343.769983
# 0.233476,0.074466,0.366872,3.135558,34.819663,0.473895,124.064119,1850.331233

# --> PW and U-learner are bad here (why?)
# --> looks nice otherwise :)

In [ ]:
# Results[0][1]
# 2.308568,1.004442,1.526483,0.028155,2.156328,2.115060,0.036090,0.033795
# 1.791405,1.193947,1.260019,0.044737,0.323602,1.588854,5.308641,0.042311
# 0.315428,0.336822,0.348231,0.023158,0.071988,0.244252,0.000031,0.017461
# 0.023137,0.060074,0.034748,0.000366,0.000355,0.008674,0.225957,0.000360

# --> nice :)

In [ ]:
# Results[0][0]
# 2.164445,0.004278,0.921012,3.660252,1.532306,1.524151,4.093397,4.733766
# 3.453443,0.004395,0.898049,4.667126,1.998041,2.072289,11.121975,5.068848
# 2.233662,0.006844,0.710762,4.107797,1.644121,1.576521,14.268573,4.718986
# 0.385062,0.001257,0.100568,0.423951,0.210232,0.208753,16.626195,0.465520


# --> nice :)

In [24]:
data[0][0][0][0]

array([[ 0.01167139,  1.13035656, -0.24136053, ..., -0.01064836,
         1.        ,  0.        ],
       [ 3.17020969,  0.22015068,  0.04529537, ...,  0.29755877,
         1.        ,  0.        ],
       [ 2.61769972,  0.37887061, -0.14322619, ...,  0.01384532,
         0.        ,  0.        ],
       ...,
       [ 9.13235505, -0.28882811, -0.20802326, ...,  0.01642092,
         1.        ,  0.        ],
       [-9.11141269, -1.15419441,  1.81805704, ...,  1.56209178,
         1.        ,  0.        ],
       [ 0.80415229,  0.12075425, -0.41938106, ..., -0.27756771,
         0.        ,  0.        ]])