In [16]:
import numpy as np

a = np.random.rand(100,20)
a

array([[0.61369386, 0.08354892, 0.58938069, ..., 0.81958122, 0.14306726,
        0.71899902],
       [0.94482668, 0.65343841, 0.26234572, ..., 0.62185733, 0.78818786,
        0.21034116],
       [0.69389205, 0.47378654, 0.89966069, ..., 0.46198304, 0.28976076,
        0.06063857],
       ...,
       [0.42917833, 0.84910995, 0.38047632, ..., 0.15181142, 0.62156104,
        0.09193815],
       [0.05276337, 0.31210915, 0.92997643, ..., 0.0167727 , 0.30304912,
        0.31030275],
       [0.8463322 , 0.41837009, 0.60964907, ..., 0.25303421, 0.14439907,
        0.75660583]])

In [ ]:
# https://www.tomstesco.com/euler-hpc-cluster/ --> HOW TO RUN ON CLUSTER!!

In [17]:
np.savetxt("try.csv", a, delimiter=',')

In [19]:
b = np.loadtxt("try.csv", delimiter=',')
b

array([[0.61369386, 0.08354892, 0.58938069, ..., 0.81958122, 0.14306726,
        0.71899902],
       [0.94482668, 0.65343841, 0.26234572, ..., 0.62185733, 0.78818786,
        0.21034116],
       [0.69389205, 0.47378654, 0.89966069, ..., 0.46198304, 0.28976076,
        0.06063857],
       ...,
       [0.42917833, 0.84910995, 0.38047632, ..., 0.15181142, 0.62156104,
        0.09193815],
       [0.05276337, 0.31210915, 0.92997643, ..., 0.0167727 , 0.30304912,
        0.31030275],
       [0.8463322 , 0.41837009, 0.60964907, ..., 0.25303421, 0.14439907,
        0.75660583]])

In [20]:
a == b

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [21]:
np.array_equal(a, b)

True

In [23]:
import pickle

In [24]:
file_name = "/Users/arberimbibaj/Documents/Master Thesis ETH/DataSets /Generated/data_synthetic.pkl"
open_file = open(file_name, "rb")
data = pickle.load(open_file)
open_file.close()

In [47]:
data[27][3][4][1]

array([[-9.40191676e+00, -3.09807076e+00,  1.95281073e+00, ...,
        -2.11360664e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.12325776e+00,  4.84823869e-01,  4.85246889e-01, ...,
         5.60131822e-01,  0.00000000e+00,  4.14461471e-01],
       [ 1.00145978e+00,  9.53999288e-01,  2.08223387e+00, ...,
         1.57723647e+00,  0.00000000e+00,  1.99142701e+00],
       ...,
       [-3.56914230e-01,  7.65487969e-02, -1.13239270e+00, ...,
         2.64481656e-02,  0.00000000e+00,  3.83920673e-11],
       [-4.88461922e+00, -1.50630822e+00,  2.10757262e-01, ...,
        -1.00177510e+00,  0.00000000e+00,  2.11031193e-12],
       [-3.75432969e+00, -1.12508111e+00,  2.82869238e-01, ...,
        -9.01363700e-01,  0.00000000e+00,  4.67016648e-10]])