In [4]:
import numpy as np

a = np.random.rand(100,20)
a

array([[0.5603774 , 0.41438161, 0.62029801, ..., 0.12356473, 0.08953473,
        0.1978213 ],
       [0.77930215, 0.67239823, 0.46538473, ..., 0.18458571, 0.19734308,
        0.29047713],
       [0.12534431, 0.1251756 , 0.3502355 , ..., 0.02888801, 0.66967862,
        0.55591174],
       ...,
       [0.18354226, 0.23242449, 0.54991868, ..., 0.9619648 , 0.745528  ,
        0.39109054],
       [0.89194518, 0.79198071, 0.51678359, ..., 0.21357919, 0.86692599,
        0.17819559],
       [0.38866436, 0.65317603, 0.87180814, ..., 0.034806  , 0.00715177,
        0.35743693]])

In [ ]:
# https://www.tomstesco.com/euler-hpc-cluster/ --> HOW TO RUN ON CLUSTER!!

In [17]:
np.savetxt("try.csv", a, delimiter=',')

In [19]:
b = np.loadtxt("try.csv", delimiter=',')
b

array([[0.61369386, 0.08354892, 0.58938069, ..., 0.81958122, 0.14306726,
        0.71899902],
       [0.94482668, 0.65343841, 0.26234572, ..., 0.62185733, 0.78818786,
        0.21034116],
       [0.69389205, 0.47378654, 0.89966069, ..., 0.46198304, 0.28976076,
        0.06063857],
       ...,
       [0.42917833, 0.84910995, 0.38047632, ..., 0.15181142, 0.62156104,
        0.09193815],
       [0.05276337, 0.31210915, 0.92997643, ..., 0.0167727 , 0.30304912,
        0.31030275],
       [0.8463322 , 0.41837009, 0.60964907, ..., 0.25303421, 0.14439907,
        0.75660583]])

In [20]:
a == b

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [21]:
np.array_equal(a, b)

True

In [5]:
import pickle

In [6]:
file_name = "/Users/arberimbibaj/Documents/Master Thesis ETH/DataSets /Generated/data_synthetic.pkl"
open_file = open(file_name, "rb")
data = pickle.load(open_file)
open_file.close()

In [7]:
data[27][3][4][1]

array([[-9.40191676e+00, -3.09807076e+00,  1.95281073e+00, ...,
        -2.11360664e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.12325776e+00,  4.84823869e-01,  4.85246889e-01, ...,
         5.60131822e-01,  0.00000000e+00,  4.14461471e-01],
       [ 1.00145978e+00,  9.53999288e-01,  2.08223387e+00, ...,
         1.57723647e+00,  0.00000000e+00,  1.99142701e+00],
       ...,
       [-3.56914230e-01,  7.65487969e-02, -1.13239270e+00, ...,
         2.64481656e-02,  0.00000000e+00,  3.83920673e-11],
       [-4.88461922e+00, -1.50630822e+00,  2.10757262e-01, ...,
        -1.00177510e+00,  0.00000000e+00,  2.11031193e-12],
       [-3.75432969e+00, -1.12508111e+00,  2.82869238e-01, ...,
        -9.01363700e-01,  0.00000000e+00,  4.67016648e-10]])

In [33]:
import jsonpickle

In [34]:
json_data = jsonpickle.encode(data)

In [ ]:
json_data

In [36]:
copy_data = jsonpickle.decode(json_data)

In [37]:
copy_data[27][3][4][1] == data[27][3][4][1]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [38]:
# save to json.file
with open("try.json", "w") as outfile:
    json.dump(json_data, outfile)

In [39]:
# open a json file
with open('try.json', 'r') as openfile:
    # Reading from json file
    json_object = json.load(openfile)

In [ ]:
json_object

In [40]:
copy_data = jsonpickle.decode(json_object)

In [41]:
copy_data[27][3][4][1]

array([[-9.40191676e+00, -3.09807076e+00,  1.95281073e+00, ...,
        -2.11360664e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.12325776e+00,  4.84823869e-01,  4.85246889e-01, ...,
         5.60131822e-01,  0.00000000e+00,  4.14461471e-01],
       [ 1.00145978e+00,  9.53999288e-01,  2.08223387e+00, ...,
         1.57723647e+00,  0.00000000e+00,  1.99142701e+00],
       ...,
       [-3.56914230e-01,  7.65487969e-02, -1.13239270e+00, ...,
         2.64481656e-02,  0.00000000e+00,  3.83920673e-11],
       [-4.88461922e+00, -1.50630822e+00,  2.10757262e-01, ...,
        -1.00177510e+00,  0.00000000e+00,  2.11031193e-12],
       [-3.75432969e+00, -1.12508111e+00,  2.82869238e-01, ...,
        -9.01363700e-01,  0.00000000e+00,  4.67016648e-10]])

In [44]:
# to open object
with open('try.json', 'r') as f:
    json_str = f.read()
    obj = jsonpickle.decode(json_str)

In [46]:
copied_data = jsonpickle.decode(obj)

In [52]:
np.array_equal(copied_data[27][3][4][1],data[27][3][4][1])

True

# THIS IS IT!

In [56]:
# SAVE LIST AS JSON FILE
f = open('tryjsonpickle.json', 'w')
json_obj = jsonpickle.encode(data)
f.write(json_obj)
f.close()

In [57]:
# LOAD JSON FILE
f = open('tryjsonpickle.json', 'r')
json_str = f.read()
obj = jsonpickle.decode(json_str)

In [60]:
np.array_equal(obj[27][3][4][1],data[27][3][4][1])

True